"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function ConcreteCalculatorClient() {
  const [length, setLength] = useState("");
  const [width, setWidth] = useState("");
  const [depth, setDepth] = useState("");

  const [lengthUnit, setLengthUnit] = useState("ft");
  const [widthUnit, setWidthUnit] = useState("ft");
  const [depthUnit, setDepthUnit] = useState("ft");

  const [result, setResult] = useState<number | null>(null);

  const convertToFeet = (value: string, unit: string) => {
    const number = parseFloat(value);

    if (unit === "m") return number * 3.28084;
    if (unit === "cm") return number / 30.48;
    if (unit === "inch") return number / 12;

    return number;
  };

  const calculateConcrete = () => {
    if (!length || !width || !depth) return;

    const lengthInFeet = convertToFeet(length, lengthUnit);
    const widthInFeet = convertToFeet(width, widthUnit);
    const depthInFeet = convertToFeet(depth, depthUnit);

    const volumeInCubicFeet =
      lengthInFeet * widthInFeet * depthInFeet;

    setResult(volumeInCubicFeet);
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setDepth("");

    setLengthUnit("ft");
    setWidthUnit("ft");
    setDepthUnit("ft");

    setResult(null);
  };

  const getVolumeInCubicMeters = () => {
    if (result === null) return 0;

    return result * 0.0283168;
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text("Concrete Calculation Report", 20, 20);

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Depth: ${depth} ${depthUnit}`,
      20,
      60
    );

    doc.text(
      `Concrete Volume: ${result.toFixed(2)} cubic feet`,
      20,
      75
    );

    doc.text(
      `Concrete Volume: ${getVolumeInCubicMeters().toFixed(
        2
      )} cubic meters`,
      20,
      85
    );

    doc.text("Generated by CalHub.in", 20, 105);

    doc.save("concrete-calculation-report.pdf");
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Concrete Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate concrete volume required
            for slabs, foundations, footings,
            columns, and construction projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) => setLength(e.target.value)}
              onKeyDown={(e) =>
                e.key === "Enter" && calculateConcrete()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter length"
            />

            <select
              value={lengthUnit}
              onChange={(e) => setLengthUnit(e.target.value)}
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">Feet (ft)</option>
              <option value="m">Meter (m)</option>
              <option value="cm">Centimeter (cm)</option>
              <option value="inch">Inch (in)</option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) => setWidth(e.target.value)}
              onKeyDown={(e) =>
                e.key === "Enter" && calculateConcrete()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter width"
            />

            <select
              value={widthUnit}
              onChange={(e) => setWidthUnit(e.target.value)}
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">Feet (ft)</option>
              <option value="m">Meter (m)</option>
              <option value="cm">Centimeter (cm)</option>
              <option value="inch">Inch (in)</option>
            </select>
          </div>

          {/* DEPTH */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Depth
            </label>

            <input
              type="number"
              min="0"
              value={depth}
              onChange={(e) => setDepth(e.target.value)}
              onKeyDown={(e) =>
                e.key === "Enter" && calculateConcrete()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter depth"
            />

            <select
              value={depthUnit}
              onChange={(e) => setDepthUnit(e.target.value)}
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">Feet (ft)</option>
              <option value="m">Meter (m)</option>
              <option value="cm">Centimeter (cm)</option>
              <option value="inch">Inch (in)</option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateConcrete}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition hover:scale-[1.02]"
            >
              Calculate Concrete
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Concrete Volume: {result.toFixed(2)} ft³
              </h2>

              <p className="mt-3 text-gray-600">
                Equivalent volume:{" "}
                {getVolumeInCubicMeters().toFixed(2)} m³
              </p>

              <p className="mt-3 text-gray-600">
                This estimated concrete volume can
                help with slabs, foundations,
                footings, driveways, and other
                construction projects.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Concrete Volume Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Concrete volume is calculated by
            multiplying length, width, and depth.
            The measurements must be converted
            into compatible units before
            calculation.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Concrete Volume = Length × Width × Depth
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This calculator helps builders,
            engineers, contractors, and
            homeowners estimate concrete
            requirements for common construction
            projects.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate volume estimation can help
            reduce material waste and improve
            construction planning.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Concrete Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>1. Enter the concrete length.</p>

            <p>2. Enter the concrete width.</p>

            <p>3. Enter the concrete depth.</p>

            <p>4. Select the correct unit for each measurement.</p>

            <p>
              5. Click calculate to get the
              estimated concrete volume.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Concrete Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            If the length is 20 ft, width is
            10 ft, and depth is 1 ft:
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = 20 × 10 × 1 = 200 ft³
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              200 ft³ ≈ 5.66 m³
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This estimated concrete volume can
            be used for slabs, foundations,
            footings, driveways, and other
            construction work.
          </p>
        </div>
      </section>

      {/* COMMON USES */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Common Concrete Calculation Uses
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>• Concrete slabs</p>
            <p>• Foundations</p>
            <p>• Footings</p>
            <p>• Driveways</p>
            <p>• Flooring and construction work</p>
            <p>• General concrete volume estimation</p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is concrete volume?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Concrete volume is the amount of
              space that needs to be filled with
              concrete. It is commonly measured
              in cubic feet or cubic meters.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is the formula for concrete volume?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              The basic formula is length ×
              width × depth. All dimensions
              should use compatible units.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I use this calculator for slabs?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. You can use it to estimate
              concrete volume for slabs,
              footings, foundations, driveways,
              and similar rectangular projects.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Does this calculator convert units?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. Length, width, and depth can
              be entered separately in feet,
              meters, centimeters, or inches.
              The calculator converts them to a
              common unit before calculating.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this concrete calculator free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, this calculator is free to use
              on CalHub.in.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}