"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function ConcreteCalculator() {
  const [length, setLength] =
    useState("");

  const [width, setWidth] =
    useState("");

  const [depth, setDepth] =
    useState("");

  const [lengthUnit, setLengthUnit] =
    useState("ft");

  const [widthUnit, setWidthUnit] =
    useState("ft");

  const [depthUnit, setDepthUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const calculateConcrete = () => {
    if (
      !length ||
      !width ||
      !depth
    )
      return;

    const volume =
      parseFloat(length) *
      parseFloat(width) *
      parseFloat(depth);

    setResult(volume);
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setDepth("");
    setLengthUnit("ft");
    setWidthUnit("ft");
    setDepthUnit("ft");
    setResult(null);
  };

  const getVolumeUnit = () => {
    if (
      lengthUnit === "m" &&
      widthUnit === "m" &&
      depthUnit === "m"
    ) {
      return "m³";
    }

    return "ft³";
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Concrete Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Depth: ${depth} ${depthUnit}`,
      20,
      60
    );

    doc.text(
      `Concrete Volume: ${result.toFixed(
        2
      )} ${getVolumeUnit()}`,
      20,
      80
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      100
    );

    doc.save(
      "concrete-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Concrete Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate concrete volume
            required for slabs,
            foundations, footings,
            columns, and construction
            projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter length"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter width"
            />

            <select
              value={widthUnit}
              onChange={(e) =>
                setWidthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* DEPTH */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Depth
            </label>

            <input
              type="number"
              min="0"
              value={depth}
              onChange={(e) =>
                setDepth(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter depth"
            />

            <select
              value={depthUnit}
              onChange={(e) =>
                setDepthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={
                calculateConcrete
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white"
            >
              Calculate Concrete
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Concrete Volume:{" "}
                {result.toFixed(2)}{" "}
                {getVolumeUnit()}
              </h2>

              <p className="mt-3 text-gray-600">
                Estimated concrete
                required for your
                construction project.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Concrete Volume Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Concrete volume is
            calculated by multiplying
            length, width, and depth.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Concrete Volume =
              Length × Width × Depth
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This calculator helps
            builders, engineers, and
            contractors estimate
            concrete requirements
            accurately.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate concrete
            estimation reduces material
            waste and improves project
            planning efficiency.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Concrete
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter slab or footing
              length.
            </p>

            <p>
              2. Enter concrete width.
            </p>

            <p>
              3. Enter concrete depth.
            </p>

            <p>
              4. Select units and click
              calculate.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Concrete
            Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            If the length is 20 ft,
            width is 10 ft, and depth
            is 1 ft:
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = 20 × 10 × 1 =
              200 ft³
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This estimated concrete
            volume can be used for
            slabs, foundations, and
            footings.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is concrete volume?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Concrete volume is the
              total amount of concrete
              required for a structure,
              measured in cubic feet or
              cubic meters.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this calculator
              accurate?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, this calculator
              provides quick and
              accurate estimates for
              standard construction
              projects.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I use this for slabs?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, this calculator can
              estimate concrete for
              slabs, footings,
              foundations, and columns.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}