"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function ExcavationCalculatorClient() {
  const [length, setLength] =
    useState("");

  const [width, setWidth] =
    useState("");

  const [depth, setDepth] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [resultUnit, setResultUnit] =
    useState("");

  const calculateExcavation = () => {
    if (
      !length ||
      !width ||
      !depth
    )
      return;

    const l =
      parseFloat(length);

    const w =
      parseFloat(width);

    const d =
      parseFloat(depth);

    if (
      isNaN(l) ||
      isNaN(w) ||
      isNaN(d) ||
      l <= 0 ||
      w <= 0 ||
      d <= 0
    )
      return;

    const volume =
      l * w * d;

    setResult(volume);

    setResultUnit(
      unit === "ft"
        ? "ft³"
        : unit === "m"
        ? "m³"
        : "cm³"
    );
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setDepth("");
    setUnit("ft");
    setResult(null);
    setResultUnit("");
  };

  const downloadPDF = () => {
    if (result === null)
      return;

    const doc =
      new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Excavation Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${unit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${unit}`,
      20,
      50
    );

    doc.text(
      `Depth: ${depth} ${unit}`,
      20,
      60
    );

    doc.text(
      `Excavation Volume: ${result.toFixed(
        2
      )} ${resultUnit}`,
      20,
      80
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      100
    );

    doc.save(
      "excavation-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Excavation Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate excavation
            volume for foundations,
            trenches, basements,
            and earthwork projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
                    {/* UNIT */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Measurement Unit
            </label>

            <select
              value={unit}
              onChange={(e) =>
                setUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>
            </select>
          </div>

          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateExcavation()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder={`Enter length (${unit})`}
            />
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateExcavation()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder={`Enter width (${unit})`}
            />
          </div>

          {/* DEPTH */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Depth
            </label>

            <input
              type="number"
              min="0"
              value={depth}
              onChange={(e) =>
                setDepth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateExcavation()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder={`Enter depth (${unit})`}
            />
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={
                calculateExcavation
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Volume
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Excavation Volume:{" "}
                {result.toFixed(2)}{" "}
                {resultUnit}
              </h2>

              <p className="mt-3 text-gray-600">
                Estimated excavation
                volume for your
                construction project.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>
            {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Excavation Volume Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Excavation volume is
            calculated by multiplying
            the excavation length,
            width, and depth using
            the same measurement
            unit.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = Length × Width ×
              Depth
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This formula is widely
            used for foundations,
            trenches, basements,
            swimming pools, retaining
            walls, and general
            earthwork estimation.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate excavation
            calculations help estimate
            labor, equipment,
            transportation, and
            disposal costs while
            reducing material waste.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This
            Excavation Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Select the preferred
              measurement unit.
            </p>

            <p>
              2. Enter excavation
              length.
            </p>

            <p>
              3. Enter excavation
              width.
            </p>

            <p>
              4. Enter excavation
              depth.
            </p>

            <p>
              5. Click Calculate
              Volume to get the total
              excavation quantity.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Excavation
            Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Suppose an excavation is
            20 ft long, 10 ft wide,
            and 5 ft deep.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = 20 × 10 × 5
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Excavation Volume =
              1,000 ft³
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This estimated excavation
            volume can be used to
            calculate soil removal,
            transportation, equipment
            requirements, and project
            costs.
          </p>
        </div>
      </section>
            {/* WHY USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Excavation Calculator?
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            This calculator helps contractors,
            engineers, builders, landscapers,
            and homeowners estimate excavation
            volume accurately before starting
            construction work.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Proper excavation estimation
            reduces material waste, equipment
            costs, transportation expenses,
            and project delays while improving
            overall project planning.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is an excavation calculator?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              An excavation calculator estimates
              the amount of soil or earth that
              needs to be removed for
              foundations, trenches, basements,
              pools, and other construction
              projects.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Which units are supported?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              You can calculate excavation
              volume using feet (ft), meters
              (m), or centimeters (cm).
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this calculator accurate?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. It provides accurate volume
              estimates based on the dimensions
              entered. Actual excavation may
              vary depending on site conditions.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this Excavation Calculator
              free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. All calculators on CalHub
              are completely free to use.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}
      