"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function CementCalculator() {
  const [length, setLength] =
    useState("");

  const [width, setWidth] =
    useState("");

  const [height, setHeight] =
    useState("");

  const [lengthUnit, setLengthUnit] =
    useState("ft");

  const [widthUnit, setWidthUnit] =
    useState("ft");

  const [heightUnit, setHeightUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const calculateCement = () => {
    if (
      !length ||
      !width ||
      !height
    )
      return;

    const volume =
      parseFloat(length) *
      parseFloat(width) *
      parseFloat(height);

    const cementBags =
      volume * 8;

    setResult(cementBags);
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setHeight("");
    setLengthUnit("ft");
    setWidthUnit("ft");
    setHeightUnit("ft");
    setResult(null);
  };

  const getVolumeUnit = () => {
    if (
      lengthUnit === "m" &&
      widthUnit === "m" &&
      heightUnit === "m"
    ) {
      return "cubic meters";
    }

    return "cubic feet";
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Cement Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Height: ${height} ${heightUnit}`,
      20,
      60
    );

    doc.text(
      `Estimated Cement Bags: ${result.toFixed(
        0
      )}`,
      20,
      75
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      100
    );

    doc.save(
      "cement-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Cement Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate cement bags
            required for concrete,
            slabs, foundations, and
            construction projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter length"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter width"
            />

            <select
              value={widthUnit}
              onChange={(e) =>
                setWidthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* HEIGHT */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Height
            </label>

            <input
              type="number"
              min="0"
              value={height}
              onChange={(e) =>
                setHeight(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter height"
            />

            <select
              value={heightUnit}
              onChange={(e) =>
                setHeightUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateCement}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white"
            >
              Calculate Cement
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Cement Bags Needed:{" "}
                {result.toFixed(0)}
              </h2>

              <p className="mt-3 text-gray-600">
                Estimated construction
                volume:{" "}
                {(
                  parseFloat(length) *
                  parseFloat(width) *
                  parseFloat(height)
                ).toFixed(2)}{" "}
                {getVolumeUnit()}
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Cement Calculation Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Cement estimation is based
            on construction volume and
            standard cement usage factor
            for concrete work.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Cement Bags = Volume × 8
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            Actual cement quantity may
            vary depending on concrete
            mix ratio, structure type,
            and material quality.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Contractors, builders, and
            engineers use cement
            calculations for slabs,
            foundations, columns, and
            construction projects.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Cement
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter construction
              length.
            </p>

            <p>
              2. Enter construction
              width.
            </p>

            <p>
              3. Enter construction
              height.
            </p>

            <p>
              4. Select units and click
              calculate.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Cement Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            If the length is 10 ft,
            width is 10 ft, and height
            is 2 ft:
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = 10 × 10 × 2 =
              200 cubic feet
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Cement Bags = 200 × 8 =
              1600 bags
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              How many cement bags are
              needed for 1 cubic meter?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Approximately 8 cement
              bags may be required
              depending on concrete mix
              ratio.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this calculator free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, all calculators on
              CalHub are completely free
              to use.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Does this include sand
              ratio?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              No, this calculator only
              estimates cement quantity.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}