"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function CementCalculatorClient() {
  const [length, setLength] = useState("");
  const [width, setWidth] = useState("");
  const [height, setHeight] = useState("");

  const [lengthUnit, setLengthUnit] = useState("ft");
  const [widthUnit, setWidthUnit] = useState("ft");
  const [heightUnit, setHeightUnit] = useState("inch");

  const [result, setResult] = useState<number | null>(null);

  const convertToFeet = (
    value: string,
    unit: string
  ) => {
    const number = parseFloat(value);

    if (unit === "m") return number * 3.28084;
    if (unit === "cm") return number / 30.48;
    if (unit === "inch") return number / 12;

    return number;
  };

  const calculateCement = () => {
    if (!length || !width || !height) return;

    const lengthInFeet = convertToFeet(
      length,
      lengthUnit
    );

    const widthInFeet = convertToFeet(
      width,
      widthUnit
    );

    const heightInFeet = convertToFeet(
      height,
      heightUnit
    );

    const volume =
      lengthInFeet *
      widthInFeet *
      heightInFeet;

    /*
      Approximate cement factor for a basic
      estimation. Actual cement requirement
      depends on concrete mix design.
    */
    const cementBags = volume * 8;

    setResult(cementBags);
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setHeight("");
    setLengthUnit("ft");
    setWidthUnit("ft");
    setHeightUnit("inch");
    setResult(null);
  };

  const getVolumeInCubicFeet = () => {
    if (!length || !width || !height) return 0;

    const lengthInFeet = convertToFeet(
      length,
      lengthUnit
    );

    const widthInFeet = convertToFeet(
      width,
      widthUnit
    );

    const heightInFeet = convertToFeet(
      height,
      heightUnit
    );

    return (
      lengthInFeet *
      widthInFeet *
      heightInFeet
    );
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Cement Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Height: ${height} ${heightUnit}`,
      20,
      60
    );

    doc.text(
      `Concrete Volume: ${getVolumeInCubicFeet().toFixed(
        2
      )} cubic feet`,
      20,
      72
    );

    doc.text(
      `Estimated Cement Bags: ${result.toFixed(
        0
      )}`,
      20,
      84
    );

    doc.text(
      "Note: Cement quantity is an approximate estimate. Actual requirements depend on concrete mix design.",
      20,
      98,
      {
        maxWidth: 170,
      }
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      120
    );

    doc.save(
      "cement-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Cement Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Estimate cement bags required
            for concrete slabs,
            foundations, floors, and
            construction projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateCement()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 20"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(e.target.value)
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="inch">
                Inch
              </option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(e.target.value)
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateCement()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 15"
            />

            <select
              value={widthUnit}
              onChange={(e) =>
                setWidthUnit(e.target.value)
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="inch">
                Inch
              </option>
            </select>
          </div>

          {/* HEIGHT */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Thickness / Height
            </label>

            <input
              type="number"
              min="0"
              value={height}
              onChange={(e) =>
                setHeight(e.target.value)
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateCement()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 6"
            />

            <select
              value={heightUnit}
              onChange={(e) =>
                setHeightUnit(e.target.value)
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="inch">
                Inch
              </option>

              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateCement}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Cement
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Estimated Cement Bags:{" "}
                {result.toFixed(0)}
              </h2>

              <p className="mt-3 text-gray-600">
                Estimated concrete volume:{" "}
                {getVolumeInCubicFeet().toFixed(
                  2
                )}{" "}
                cubic feet.
              </p>

              <p className="mt-3 text-sm leading-6 text-gray-500">
                This is an approximate
                estimate. Actual cement
                requirements depend on the
                concrete mix ratio, grade,
                wastage, and project
                specifications.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Cement Calculation Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Cement estimation starts with
            calculating the concrete volume
            from length, width, and
            thickness or height. The
            calculator converts the entered
            measurements to feet before
            calculating the volume.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = Length × Width ×
              Thickness
            </p>

            <p className="mt-4 text-lg font-semibold text-gray-700">
              Estimated Cement Bags =
              Volume × 8
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            The cement factor used here is
            only a basic estimation
            assumption. Actual cement
            quantity should be determined
            from the required concrete mix
            design and project
            specifications.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Cement
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter the construction
              length.
            </p>

            <p>
              2. Enter the construction
              width.
            </p>

            <p>
              3. Enter the slab thickness
              or construction height.
            </p>

            <p>
              4. Select the appropriate
              units.
            </p>

            <p>
              5. Click Calculate Cement to
              get the estimated number of
              cement bags.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Cement Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Suppose a concrete area is 20
            ft long, 10 ft wide, and has a
            thickness of 6 inches.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-xl font-bold text-orange-600">
              Thickness = 6 ÷ 12 = 0.5
              ft
            </p>

            <p className="mt-3 text-xl font-bold text-orange-600">
              Volume = 20 × 10 × 0.5 = 100
              cubic feet
            </p>

            <p className="mt-3 text-xl font-semibold text-gray-700">
              Estimated Cement = 100 × 8 =
              800 bags
            </p>
          </div>

          <p className="mt-5 text-sm leading-6 text-gray-500">
            This example uses the same
            approximate factor as the
            calculator. Actual cement
            consumption can be significantly
            different depending on the
            concrete mix design.
          </p>
        </div>
      </section>

      {/* IMPORTANT NOTE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl border border-orange-200 bg-orange-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Important Cement Estimation
            Note
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Cement requirement cannot be
            determined accurately from
            volume alone. Concrete grade,
            mix proportion, cement type,
            aggregate properties, water
            content, and project
            specifications can all affect
            the final quantity.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Use this calculator as a quick
            planning estimate. For
            structural work, always follow
            the approved mix design and
            advice of a qualified
            construction professional.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What does a cement
              calculator calculate?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              It provides an approximate
              estimate of cement bags based
              on the calculated concrete
              volume and an assumed cement
              factor.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              How many cement bags are
              needed for concrete?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              The exact number depends on
              the concrete mix design and
              required strength. This
              calculator provides only a
              basic estimate.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I use this for a concrete
              slab?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. Enter the slab length,
              width, and thickness to
              estimate the concrete volume
              and approximate cement
              requirement.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Does this calculator include
              sand and aggregate?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              No. This calculator estimates
              cement only. Sand and
              aggregate requirements need
              separate calculations based
              on the selected concrete mix.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this cement calculator
              free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, the CalHub cement
              calculator is free to use.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}