"use client";

import { useState } from "react";
import jsPDF from "jspdf";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function UnitConverterClient() {
  const [value, setValue] =
    useState("");

  const [fromUnit, setFromUnit] =
    useState("m");

  const [toUnit, setToUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const conversionFactors: {
    [key: string]: number;
  } = {
    m: 1,
    ft: 3.28084,
    cm: 100,
    inch: 39.3701,
  };

  const convertUnits = () => {
    if (!value) return;

    const meters =
      parseFloat(value) /
      conversionFactors[fromUnit];

    const converted =
      meters *
      conversionFactors[toUnit];

    setResult(converted);
  };

  const resetCalculator = () => {
    setValue("");
    setFromUnit("m");
    setToUnit("ft");
    setResult(null);
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Unit Conversion Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Input Value: ${value} ${fromUnit}`,
      20,
      40
    );

    doc.text(
      `Converted Value: ${result.toFixed(
        4
      )} ${toUnit}`,
      20,
      50
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      80
    );

    doc.save(
      "unit-conversion-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO SECTION */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Unit Converter for
            Construction &
            Engineering
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Convert meters, feet,
            inches, and centimeters
            instantly for construction,
            architecture, engineering,
            and measurement projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          {/* VALUE */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Enter Value
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={value}
              onChange={(e) =>
                setValue(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                convertUnits()
              }
              placeholder="e.g. 10"
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* FROM UNIT */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              From Unit
            </label>

            <select
              value={fromUnit}
              onChange={(e) =>
                setFromUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="m">
                Meter (m)
              </option>

              <option value="ft">
                Feet (ft)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="inch">
                Inch
              </option>
            </select>
          </div>

          {/* TO UNIT */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              To Unit
            </label>

            <select
              value={toUnit}
              onChange={(e) =>
                setToUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="m">
                Meter (m)
              </option>

              <option value="ft">
                Feet (ft)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="inch">
                Inch
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={
                convertUnits
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Convert Units
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">

              <h2 className="text-2xl font-bold text-gray-900">
                Result:
                {" "}
                {result.toFixed(4)}
                {" "}
                {toUnit}
              </h2>

              <p className="mt-3 text-gray-600">
                Converted value from
                {` ${fromUnit} `}
                to
                {` ${toUnit} `}
                using standard
                measurement conversion
                factors.
              </p>

              <button
                onClick={
                  downloadPDF
                }
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
              >
                Download PDF
                Report
              </button>
            </div>
          )}
        </div>
      </section>
            {/* FORMULA */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Unit Conversion Formula
          </h2>

          <p className="mt-4 text-gray-600">
            Unit conversion is performed by
            converting the selected value to
            a base unit and then converting
            it into the target unit.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Common Formula
            </h3>

            <p className="mt-3 text-lg font-medium text-orange-600">
              Feet = Meters × 3.28084
            </p>
          </div>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            How to Use This Unit
            Converter
          </h2>

          <p className="mt-4 text-gray-600">
            Enter a value, choose the
            source unit and target unit,
            then click Convert Units. The
            calculator instantly displays
            the converted result.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Example Conversion
            </h3>

            <p className="mt-3 text-gray-600">
              10 meters × 3.28084
            </p>

            <p className="mt-3 font-medium text-orange-600">
              = 32.8084 feet
            </p>
          </div>
        </div>
      </section>

      {/* COMMON EXAMPLES */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Common Conversion Examples
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • 1 meter = 3.28084 feet
            </p>

            <p>
              • 1 meter = 100 centimeters
            </p>

            <p>
              • 1 meter = 39.3701 inches
            </p>

            <p>
              • 1 foot = 12 inches
            </p>

            <p>
              • 10 meters = 32.8084 feet
            </p>
          </div>
        </div>
      </section>

      {/* CONVERSION GUIDE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Measurement Conversion Guide
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • Meter (m) – SI base unit
              of length
            </p>

            <p>
              • Feet (ft) – commonly used
              in construction
            </p>

            <p>
              • Inch – used for detailed
              measurements
            </p>

            <p>
              • Centimeter (cm) – metric
              unit for smaller dimensions
            </p>
          </div>
        </div>
      </section>

      {/* WHY USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Unit
            Converter?
          </h2>

          <p className="mt-4 text-gray-600">
            This converter helps builders,
            engineers, architects,
            contractors, and homeowners
            quickly convert measurements
            without manual calculations.
          </p>

          <p className="mt-4 text-gray-600">
            Accurate unit conversion helps
            reduce measurement errors and
            improves planning for
            construction, renovation, and
            engineering projects.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What is a unit converter?
              </h3>

              <p className="mt-2 text-gray-600">
                A unit converter allows you
                to convert measurements
                between different units
                instantly and accurately.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I use this for
                construction projects?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. This converter is
                useful for construction,
                architecture, engineering,
                and renovation projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Which units are supported?
              </h3>

              <p className="mt-2 text-gray-600">
                Meter, feet, inch, and
                centimeter conversions are
                supported.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this converter accurate?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. Standard conversion
                factors are used to provide
                accurate results.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. All calculators and
                conversion tools on CalHub
                are completely free.
              </p>
            </div>

          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}