"use client";

import { useState } from "react";
import jsPDF from "jspdf";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function GravelCalculatorClient() {
  const [length, setLength] =
    useState("");

  const [width, setWidth] =
    useState("");

  const [depth, setDepth] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [tons, setTons] =
    useState<number | null>(null);

  const [resultUnit, setResultUnit] =
    useState("");

  const convertToFeet = (
    value: number
  ) => {
    switch (unit) {
      case "m":
        return value * 3.28084;

      case "cm":
        return value * 0.0328084;

      case "yd":
        return value * 3;

      default:
        return value;
    }
  };

  const calculateGravel = () => {
    if (
      !length ||
      !width ||
      !depth
    ) {
      return;
    }

    const lengthFt =
      convertToFeet(
        parseFloat(length)
      );

    const widthFt =
      convertToFeet(
        parseFloat(width)
      );

    const depthFt =
      convertToFeet(
        parseFloat(depth)
      );

    const volumeFt =
      lengthFt *
      widthFt *
      depthFt;

    let finalVolume =
      volumeFt;

    let volumeUnit =
      "ft³";

    if (unit === "m") {
      finalVolume =
        volumeFt * 0.0283168;

      volumeUnit = "m³";
    }

    if (unit === "cm") {
      finalVolume =
        volumeFt * 28316.8;

      volumeUnit = "cm³";
    }

    if (unit === "yd") {
      finalVolume =
        volumeFt / 27;

      volumeUnit = "yd³";
    }

    const estimatedTons =
      volumeFt * 0.05;

    setResult(finalVolume);

    setResultUnit(
      volumeUnit
    );

    setTons(
      estimatedTons
    );
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setDepth("");
    setUnit("ft");
    setResult(null);
    setResultUnit("");
    setTons(null);
  };

  const downloadPDF = () => {
    if (
      result === null ||
      tons === null
    ) {
      return;
    }

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Gravel Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${unit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${unit}`,
      20,
      50
    );

    doc.text(
      `Depth: ${depth} ${unit}`,
      20,
      60
    );

    doc.text(
      `Gravel Volume: ${result.toFixed(
        2
      )} ${resultUnit}`,
      20,
      75
    );

    doc.text(
      `Estimated Weight: ${tons.toFixed(
        2
      )} tons`,
      20,
      90
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      120
    );

    doc.save(
      "gravel-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Gravel Calculator for
            Driveways, Landscaping &
            Construction
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate gravel volume,
            material quantity, and
            estimated weight instantly
            for driveways, pathways,
            foundations, drainage,
            landscaping, and
            construction projects.
          </p>
        </div>

        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
                    <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Unit
            </label>

            <select
              value={unit}
              onChange={(e) =>
                setUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="yd">
                Yard (yd)
              </option>
            </select>
          </div>

          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter length"
            />
          </div>

          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter width"
            />
          </div>

          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Depth ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={depth}
              onChange={(e) =>
                setDepth(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter depth"
            />
          </div>

          <div className="flex gap-4">
            <button
              onClick={
                calculateGravel
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Gravel
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {result !== null &&
            tons !== null && (
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
                <h2 className="text-2xl font-bold text-gray-900">
                  Gravel Volume:
                  {" "}
                  {result.toFixed(
                    2
                  )}{" "}
                  {resultUnit}
                </h2>

                <p className="mt-3 text-lg text-gray-700">
                  Estimated Weight:
                  {" "}
                  {tons.toFixed(
                    2
                  )}{" "}
                  tons
                </p>

                <p className="mt-3 text-gray-600">
                  This estimate helps
                  determine gravel
                  quantity required for
                  driveways, pathways,
                  drainage systems,
                  landscaping, and
                  foundation projects.
                </p>

                <button
                  onClick={
                    downloadPDF
                  }
                  className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
                >
                  Download PDF Report
                </button>
              </div>
            )}
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Gravel Calculation Formula
          </h2>

          <p className="mt-4 text-gray-600">
            Gravel volume is calculated
            by multiplying length,
            width, and depth of the
            area being filled.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Formula
            </h3>

            <p className="mt-3 text-lg font-medium text-orange-600">
              Gravel Volume =
              Length × Width × Depth
            </p>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Common Gravel Uses
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • Driveways and parking
              areas
            </p>

            <p>
              • Landscaping and garden
              paths
            </p>

            <p>
              • Drainage systems
            </p>

            <p>
              • Building foundations
            </p>

            <p>
              • Walkways and outdoor
              flooring
            </p>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                How much gravel do I
                need?
              </h3>

              <p className="mt-2 text-gray-600">
                Enter the project
                length, width, and
                depth to estimate
                gravel volume
                instantly.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I use this for
                driveways?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes, this calculator is
                suitable for driveways,
                pathways, landscaping,
                foundations, and
                drainage projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Does it estimate
                gravel weight?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes, the calculator
                provides an approximate
                gravel weight in tons
                based on volume.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator
                free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes, all calculators on
                CalHub are completely
                free to use.
              </p>
            </div>

          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}