"use client";

import { useState } from "react";
import jsPDF from "jspdf";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function GravelCalculatorClient() {
  const [length, setLength] =
    useState("");

  const [width, setWidth] =
    useState("");

  const [depth, setDepth] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [tons, setTons] =
    useState<number | null>(null);

  const [resultUnit, setResultUnit] =
    useState("");

  const calculateGravel = () => {
    if (
      !length ||
      !width ||
      !depth
    )
      return;

    const l = parseFloat(length);
    const w = parseFloat(width);
    const d = parseFloat(depth);

    if (
      isNaN(l) ||
      isNaN(w) ||
      isNaN(d) ||
      l <= 0 ||
      w <= 0 ||
      d <= 0
    )
      return;

    const volume =
      l * w * d;

    setResult(volume);

    setResultUnit(
      unit === "ft"
        ? "ft³"
        : unit === "m"
        ? "m³"
        : unit === "cm"
        ? "cm³"
        : "yd³"
    );

    setTons(volume * 0.05);
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setDepth("");
    setUnit("ft");
    setResult(null);
    setResultUnit("");
    setTons(null);
  };

  const downloadPDF = () => {
    if (
      result === null ||
      tons === null
    )
      return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Gravel Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${unit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${unit}`,
      20,
      50
    );

    doc.text(
      `Depth: ${depth} ${unit}`,
      20,
      60
    );

    doc.text(
      `Gravel Volume: ${result.toFixed(
        2
      )} ${resultUnit}`,
      20,
      75
    );

    doc.text(
      `Estimated Weight: ${tons.toFixed(
        2
      )} tons`,
      20,
      90
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      110
    );

    doc.save(
      "gravel-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Gravel Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate gravel volume
            and estimated weight for
            driveways, landscaping,
            foundations, drainage,
            and construction projects.
          </p>
        </div>

        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
                    {/* UNIT */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Measurement Unit
            </label>

            <select
              value={unit}
              onChange={(e) =>
                setUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="yd">
                Yard (yd)
              </option>
            </select>
          </div>

          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateGravel()
              }
              placeholder="e.g. 20"
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateGravel()
              }
              placeholder="e.g. 10"
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* DEPTH */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Depth ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={depth}
              onChange={(e) =>
                setDepth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateGravel()
              }
              placeholder="e.g. 4"
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={
                calculateGravel
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Gravel
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null &&
            tons !== null && (
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
                <h2 className="text-2xl font-bold text-gray-900">
                  Gravel Volume:{" "}
                  {result.toFixed(
                    2
                  )}{" "}
                  {resultUnit}
                </h2>

                <p className="mt-3 text-lg font-semibold text-gray-700">
                  Estimated Weight:{" "}
                  {tons.toFixed(
                    2
                  )}{" "}
                  tons
                </p>

                <p className="mt-3 text-gray-600">
                  Estimate gravel
                  quantity for driveways,
                  landscaping, drainage,
                  foundations, and other
                  construction projects.
                </p>

                <button
                  onClick={
                    downloadPDF
                  }
                  className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
                >
                  Download PDF Report
                </button>
              </div>
            )}
        </div>
      </section>
            {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Gravel Calculation Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Gravel volume is calculated by
            multiplying the project
            length, width, and depth
            using the same unit of
            measurement.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = Length × Width ×
              Depth
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            After calculating the
            volume, the approximate
            gravel weight is estimated
            using an average gravel
            density to help with
            ordering materials.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Gravel
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Select your preferred
              measurement unit.
            </p>

            <p>
              2. Enter the project
              length.
            </p>

            <p>
              3. Enter the project
              width.
            </p>

            <p>
              4. Enter the gravel
              depth.
            </p>

            <p>
              5. Click Calculate Gravel
              to estimate the required
              volume and weight.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Suppose your project area
            is 20 ft long, 10 ft wide,
            and 4 ft deep.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Volume = 20 × 10 × 4
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Gravel Volume = 800 ft³
            </p>

            <p className="mt-2 text-lg text-gray-700">
              Estimated Weight ≈ 40
              tons
            </p>
          </div>
        </div>
      </section>
            {/* WHY USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Gravel
            Calculator?
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            This calculator helps
            homeowners, contractors,
            landscapers, and builders
            estimate gravel quantity
            quickly before purchasing
            materials.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate estimates reduce
            material waste, save money,
            and improve planning for
            driveways, walkways,
            drainage systems,
            foundations, and
            landscaping projects.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">
            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What is a gravel
                calculator?
              </h3>

              <p className="mt-2 text-gray-600">
                A gravel calculator
                estimates the amount of
                gravel required based on
                the length, width, and
                depth of an area.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I use this for
                driveways?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. It is suitable for
                driveways, walkways,
                patios, landscaping,
                drainage systems, and
                foundation projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Does it estimate
                gravel weight?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. The calculator
                provides an approximate
                gravel weight in tons to
                help with material
                planning.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator
                free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. All calculators on
                CalHub are completely
                free to use without any
                registration.
              </p>
            </div>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}