"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function FlooringCalculatorClient() {
  const [roomLength, setRoomLength] =
    useState("");

  const [roomWidth, setRoomWidth] =
    useState("");

  const [flooringCost, setFlooringCost] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [area, setArea] =
    useState<number | null>(null);

  const [result, setResult] =
    useState<number | null>(null);

  const [areaUnit, setAreaUnit] =
    useState("");

  const calculateFlooring = () => {
    if (
      !roomLength ||
      !roomWidth ||
      !flooringCost
    )
      return;

    const length =
      parseFloat(roomLength);

    const width =
      parseFloat(roomWidth);

    const cost =
      parseFloat(flooringCost);

    if (
      isNaN(length) ||
      isNaN(width) ||
      isNaN(cost) ||
      length <= 0 ||
      width <= 0 ||
      cost <= 0
    )
      return;

    const totalArea =
      length * width;

    const totalCost =
      totalArea * cost;

    setArea(totalArea);

    setAreaUnit(
      unit === "ft"
        ? "sq ft"
        : unit === "m"
        ? "sq m"
        : "sq cm"
    );

    setResult(totalCost);
  };

  const resetCalculator = () => {
    setRoomLength("");
    setRoomWidth("");
    setFlooringCost("");
    setUnit("ft");
    setArea(null);
    setAreaUnit("");
    setResult(null);
  };

  const downloadPDF = () => {
    if (
      area === null ||
      result === null
    )
      return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Flooring Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Room Length: ${roomLength} ${unit}`,
      20,
      40
    );

    doc.text(
      `Room Width: ${roomWidth} ${unit}`,
      20,
      50
    );

    doc.text(
      `Flooring Cost: ₹${flooringCost}`,
      20,
      60
    );

    doc.text(
      `Floor Area: ${area.toFixed(
        2
      )} ${areaUnit}`,
      20,
      75
    );

    doc.text(
      `Estimated Cost: ₹${result.toLocaleString()}`,
      20,
      85
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      110
    );

    doc.save(
      "flooring-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Flooring Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate flooring area
            and estimated flooring
            cost for tile, wood,
            vinyl, laminate, and
            marble flooring projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
                    {/* UNIT */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Measurement Unit
            </label>

            <select
              value={unit}
              onChange={(e) =>
                setUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>
            </select>
          </div>

          {/* ROOM LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Room Length ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={roomLength}
              onChange={(e) =>
                setRoomLength(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateFlooring()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 20"
            />
          </div>

          {/* ROOM WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Room Width ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={roomWidth}
              onChange={(e) =>
                setRoomWidth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateFlooring()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 15"
            />
          </div>

          {/* FLOORING COST */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Flooring Cost Per Unit
            </label>

            <input
              type="number"
              min="0"
              value={flooringCost}
              onChange={(e) =>
                setFlooringCost(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateFlooring()
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 120"
            />
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={
                calculateFlooring
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Flooring
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {area !== null &&
            result !== null && (
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
                <h2 className="text-2xl font-bold text-gray-900">
                  Total Area:{" "}
                  {area.toFixed(2)}{" "}
                  {areaUnit}
                </h2>

                <p className="mt-3 text-xl font-semibold text-gray-700">
                  Estimated Cost: ₹
                  {result.toLocaleString()}
                </p>

                <p className="mt-2 text-gray-600">
                  Estimated flooring
                  material cost based
                  on the entered room
                  dimensions.
                </p>

                <button
                  onClick={
                    downloadPDF
                  }
                  className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
                >
                  Download PDF Report
                </button>
              </div>
            )}
        </div>
      </section>
            {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Flooring Area Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Flooring area is
            calculated by multiplying
            the room length by the
            room width using the same
            unit of measurement.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Area = Length × Width
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            Once the floor area is
            calculated, multiply it by
            the flooring cost per unit
            area to estimate the total
            project cost.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate flooring
            calculations help reduce
            material waste and improve
            budgeting for tile,
            hardwood, laminate,
            marble, and vinyl flooring
            installations.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Flooring
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Select your preferred
              measurement unit.
            </p>

            <p>
              2. Enter the room
              length.
            </p>

            <p>
              3. Enter the room
              width.
            </p>

            <p>
              4. Enter flooring cost
              per unit area.
            </p>

            <p>
              5. Click Calculate
              Flooring to estimate the
              total area and project
              cost.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Flooring
            Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Suppose a room measures
            20 ft × 15 ft and the
            flooring costs ₹120 per
            square foot.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Area = 20 × 15 = 300 sq
              ft
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Total Cost = ₹36,000
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This estimate helps plan
            flooring material,
            installation budget, and
            overall renovation costs.
          </p>
        </div>
      </section>
            {/* WHY USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Flooring
            Calculator?
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            This calculator helps
            homeowners, contractors,
            builders, and interior
            designers estimate flooring
            area and project cost before
            purchasing materials.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate flooring
            estimation minimizes
            material waste, improves
            budgeting, and simplifies
            planning for residential
            and commercial flooring
            projects.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is a flooring
              calculator?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              A flooring calculator
              estimates the floor area
              and total flooring cost
              using room dimensions and
              the cost per unit area.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I use this calculator
              for tiles and hardwood?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. It works for tile,
              hardwood, laminate,
              vinyl, marble, carpet,
              and most other flooring
              materials.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Does it include labor
              charges?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              No. The calculator
              estimates flooring
              material cost only.
              Installation and labor
              costs should be added
              separately if required.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this Flooring
              Calculator free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. All calculators on
              CalHub are completely
              free to use without any
              registration.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}