"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function ConstructionCostCalculatorClient() {
  const [area, setArea] = useState("");
  const [costPerUnit, setCostPerUnit] = useState("");
  const [areaUnit, setAreaUnit] = useState("sq ft");
  const [currency, setCurrency] = useState("₹");

  const [result, setResult] = useState<number | null>(null);

  const calculateCost = () => {
    const areaValue = parseFloat(area);
    const costValue = parseFloat(costPerUnit);

    if (
      !Number.isFinite(areaValue) ||
      !Number.isFinite(costValue) ||
      areaValue <= 0 ||
      costValue < 0
    ) {
      setResult(null);
      return;
    }

    const totalCost = areaValue * costValue;

    setResult(totalCost);
  };

  const resetCalculator = () => {
    setArea("");
    setCostPerUnit("");
    setAreaUnit("sq ft");
    setCurrency("₹");
    setResult(null);
  };

  const formatNumber = (value: number) => {
    return value.toLocaleString("en-IN", {
      maximumFractionDigits: 2,
    });
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("Construction Cost Report", 20, 20);

    doc.setFontSize(12);

    doc.text(
      `Construction Area: ${area} ${areaUnit}`,
      20,
      40
    );

    doc.text(
      `Cost Per ${areaUnit}: ${currency}${formatNumber(
        parseFloat(costPerUnit)
      )}`,
      20,
      50
    );

    doc.text(
      `Estimated Construction Cost: ${currency}${formatNumber(
        result
      )}`,
      20,
      65
    );

    doc.text(
      "Note: Actual construction costs may vary depending on location, materials, labor, design, and project requirements.",
      20,
      80,
      {
        maxWidth: 170,
      }
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      105
    );

    doc.save("construction-cost-report.pdf");
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Construction Cost Calculator
          </h1>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Estimate construction costs for
            houses, apartments, commercial
            buildings, renovation projects,
            and other construction work.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          {/* AREA */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Construction Area
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={area}
              onChange={(e) => setArea(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateCost();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 2000"
            />

            <select
              value={areaUnit}
              onChange={(e) => setAreaUnit(e.target.value)}
              className="mt-3 w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="sq ft">
                Square Feet (sq ft)
              </option>

              <option value="sq m">
                Square Meter (sq m)
              </option>
            </select>
          </div>

          {/* COST */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Cost Per {areaUnit}
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={costPerUnit}
              onChange={(e) =>
                setCostPerUnit(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateCost();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 2000"
            />

            <select
              value={currency}
              onChange={(e) => setCurrency(e.target.value)}
              className="mt-3 w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="₹">INR (₹)</option>
              <option value="$">USD ($)</option>
              <option value="€">Euro (€)</option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateCost}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02] hover:shadow-lg"
            >
              Calculate Cost
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Estimated Cost:{" "}
                {currency}
                {formatNumber(result)}
              </h2>

              <p className="mt-3 text-gray-600">
                Based on{" "}
                {formatNumber(parseFloat(area))}{" "}
                {areaUnit} at a construction
                rate of{" "}
                {currency}
                {formatNumber(
                  parseFloat(costPerUnit)
                )}{" "}
                per {areaUnit}.
              </p>

              <p className="mt-3 text-sm leading-6 text-gray-500">
                Actual construction costs may
                vary depending on location,
                material quality, labor charges,
                design, and project requirements.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Construction Cost Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Construction cost can be estimated
            by multiplying the total
            construction area by the cost per
            square foot or square meter.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <h3 className="text-2xl font-semibold text-gray-900">
              Formula
            </h3>

            <p className="mt-3 text-2xl font-bold text-orange-600">
              Construction Cost =
              Area × Cost Per Unit
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            For example, if the construction
            area is 2,000 sq ft and the
            construction rate is ₹2,000 per
            sq ft:
          </p>

          <p className="mt-4 font-semibold text-gray-800">
            ₹2,000 × 2,000 = ₹40,00,000
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            This is a basic estimation method.
            Final project costs may include
            materials, labor, permits,
            architectural fees, electrical
            work, plumbing, finishing, and
            other expenses.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Construction
            Cost Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter the total construction
              area.
            </p>

            <p>
              2. Select square feet or square
              meter.
            </p>

            <p>
              3. Enter the construction cost
              per selected unit.
            </p>

            <p>
              4. Select your preferred currency.
            </p>

            <p>
              5. Click Calculate Cost to see
              the estimated project cost.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Construction Cost
            Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Suppose a house has a total
            construction area of 2,000 sq ft
            and the estimated construction
            rate is ₹2,000 per sq ft.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-xl font-semibold text-gray-700">
              Area = 2,000 sq ft
            </p>

            <p className="mt-3 text-xl font-semibold text-gray-700">
              Rate = ₹2,000 per sq ft
            </p>

            <p className="mt-4 text-2xl font-bold text-orange-600">
              Cost = 2,000 × ₹2,000
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-800">
              Estimated Cost = ₹40,00,000
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            The actual cost can be higher or
            lower depending on location,
            building design, labor rates,
            materials, finishing quality, and
            other project-specific expenses.
          </p>
        </div>
      </section>

      {/* FACTORS */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Factors That Affect Construction
            Cost
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • Location and local labor rates
            </p>

            <p>
              • Quality and quantity of
              construction materials
            </p>

            <p>
              • Building design and structural
              requirements
            </p>

            <p>
              • Flooring, painting, doors, and
              windows
            </p>

            <p>
              • Electrical and plumbing work
            </p>

            <p>
              • Interior finishing and fixtures
            </p>

            <p>
              • Architectural, engineering, and
              approval costs
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is a construction cost
              calculator?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              A construction cost calculator
              provides a quick estimate of
              building costs using the total
              construction area and estimated
              cost per unit.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I use this for house
              construction?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. You can use it for an
              initial estimate for houses,
              apartments, offices, commercial
              buildings, and renovation
              projects.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Does the calculator give the
              exact construction cost?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              No. It provides an estimated
              cost. Actual expenses depend on
              materials, labor, location,
              design, finishing, and other
              project requirements.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I calculate cost per square
              meter?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes. Select Square Meter from
              the area unit dropdown and enter
              the corresponding cost per square
              meter.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this calculator free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, the construction cost
              calculator on CalHub is free to
              use.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}