"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function ConstructionCostCalculator() {
  const [area, setArea] =
    useState("");

  const [costPerSqft, setCostPerSqft] =
    useState("");

  const [areaUnit, setAreaUnit] =
    useState("sq ft");

  const [currency, setCurrency] =
    useState("₹");

  const [result, setResult] =
    useState<number | null>(null);

  const calculateCost = () => {
    if (!area || !costPerSqft)
      return;

    const totalCost =
      parseFloat(area) *
      parseFloat(costPerSqft);

    setResult(totalCost);
  };

  const resetCalculator = () => {
    setArea("");
    setCostPerSqft("");
    setAreaUnit("sq ft");
    setCurrency("₹");
    setResult(null);
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Construction Cost Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Area: ${area} ${areaUnit}`,
      20,
      40
    );

    doc.text(
      `Cost Per Unit: ${currency}${costPerSqft}`,
      20,
      50
    );

    doc.text(
      `Estimated Cost: ${currency}${result.toLocaleString()}`,
      20,
      70
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      100
    );

    doc.save(
      "construction-cost-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Construction Cost
            Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Estimate construction
            costs for houses,
            apartments, commercial
            buildings, and renovation
            projects instantly.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* AREA */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Construction Area
            </label>

            <input
              type="number"
              min="0"
              value={area}
              onChange={(e) =>
                setArea(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter total area"
            />

            <select
              value={areaUnit}
              onChange={(e) =>
                setAreaUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="sq ft">
                Square Feet
              </option>

              <option value="sq m">
                Square Meter
              </option>
            </select>
          </div>

          {/* COST */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Cost Per Unit
            </label>

            <input
              type="number"
              min="0"
              value={costPerSqft}
              onChange={(e) =>
                setCostPerSqft(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter cost"
            />

            <select
              value={currency}
              onChange={(e) =>
                setCurrency(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="₹">
                INR (₹)
              </option>

              <option value="$">
                USD ($)
              </option>

              <option value="€">
                Euro (€)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateCost}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white"
            >
              Calculate Cost
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Estimated Cost:{" "}
                {currency}
                {result.toLocaleString()}
              </h2>

              <p className="mt-3 text-gray-600">
                Estimated project cost
                based on selected area
                and construction rate.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Construction Cost Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Construction cost is
            estimated by multiplying
            total construction area by
            the cost per square foot or
            square meter.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Construction Cost =
              Area × Cost Per Unit
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            Builders, contractors,
            engineers, and homeowners
            use construction cost
            calculations during project
            planning and budgeting.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate cost estimation
            helps reduce budget
            overruns and improves
            financial planning for
            construction projects.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This
            Construction Cost
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter total
              construction area.
            </p>

            <p>
              2. Select square feet or
              square meter unit.
            </p>

            <p>
              3. Enter cost per unit.
            </p>

            <p>
              4. Click calculate to get
              estimated construction
              cost instantly.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Construction
            Cost Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            If the construction area
            is 2,000 sq ft and the
            cost is ₹2,000 per sq ft:
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Cost = 2,000 × 2,000
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Estimated Cost =
              ₹40,00,000
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            Actual construction costs
            may vary depending on
            location, labor, material
            quality, and project type.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              What is a construction
              cost calculator?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              A construction cost
              calculator helps estimate
              building project costs
              based on area and
              construction rate.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Can I use this for house
              construction?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, this calculator is
              useful for houses,
              apartments, offices, and
              renovation projects.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this calculator free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, all calculators on
              CalHub are completely
              free to use.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}