"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

type Unit = "ft" | "m";

export default function BrickCalculatorClient() {
  const [length, setLength] = useState("");
  const [height, setHeight] = useState("");

  const [lengthUnit, setLengthUnit] =
    useState<Unit>("ft");

  const [heightUnit, setHeightUnit] =
    useState<Unit>("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [wallArea, setWallArea] =
    useState<number | null>(null);

  const [areaUnit, setAreaUnit] =
    useState("sq ft");

  const convertToFeet = (
    value: number,
    unit: Unit
  ) => {
    if (unit === "m") {
      return value * 3.280839895;
    }

    return value;
  };

  const calculateBricks = () => {
    if (!length || !height) return;

    const lengthValue =
      parseFloat(length);

    const heightValue =
      parseFloat(height);

    if (
      isNaN(lengthValue) ||
      isNaN(heightValue) ||
      lengthValue <= 0 ||
      heightValue <= 0
    ) {
      return;
    }

    const lengthInFeet =
      convertToFeet(
        lengthValue,
        lengthUnit
      );

    const heightInFeet =
      convertToFeet(
        heightValue,
        heightUnit
      );

    const calculatedArea =
      lengthInFeet * heightInFeet;

    const bricksNeeded =
      calculatedArea * 50;

    setWallArea(calculatedArea);
    setResult(bricksNeeded);
    setAreaUnit("sq ft");
  };

  const resetCalculator = () => {
    setLength("");
    setHeight("");
    setLengthUnit("ft");
    setHeightUnit("ft");
    setResult(null);
    setWallArea(null);
    setAreaUnit("sq ft");
  };

  const downloadPDF = () => {
    if (
      result === null ||
      wallArea === null
    ) {
      return;
    }

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Brick Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Wall Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Wall Height: ${height} ${heightUnit}`,
      20,
      50
    );

    doc.text(
      `Wall Area: ${wallArea.toFixed(
        2
      )} ${areaUnit}`,
      20,
      60
    );

    doc.text(
      "Estimated Bricks Required: " +
        result.toFixed(0),
      20,
      70
    );

    doc.text(
      "Calculation Basis: 50 bricks per square foot",
      20,
      80
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      100
    );

    doc.save(
      "brick-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Brick Calculator for Wall
            Construction
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Estimate the number of bricks
            required for wall construction,
            buildings, boundary walls, and
            masonry projects using wall
            length and height.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Wall Length
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateBricks();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 20"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(
                  e.target.value as Unit
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* HEIGHT */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Wall Height
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={height}
              onChange={(e) =>
                setHeight(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateBricks();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 10"
            />

            <select
              value={heightUnit}
              onChange={(e) =>
                setHeightUnit(
                  e.target.value as Unit
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateBricks}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Bricks
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null &&
            wallArea !== null && (
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
                <h2 className="text-2xl font-bold text-gray-900">
                  Estimated Bricks Needed:{" "}
                  {result.toFixed(0)}
                </h2>

                <p className="mt-3 text-gray-600">
                  Wall Area:{" "}
                  {wallArea.toFixed(2)}{" "}
                  {areaUnit}
                </p>

                <p className="mt-3 text-gray-600">
                  Based on an estimate of
                  50 bricks per square foot,
                  approximately{" "}
                  {result.toFixed(0)}{" "}
                  bricks are required.
                </p>

                <p className="mt-3 text-sm text-gray-500">
                  Actual brick quantity can
                  vary depending on brick
                  dimensions, mortar joints,
                  wall thickness, openings,
                  and construction method.
                </p>

                <button
                  onClick={downloadPDF}
                  className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
                >
                  Download PDF Report
                </button>
              </div>
            )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Brick Calculation Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Brick estimation starts by
            calculating the total wall
            area from its length and
            height. The wall area is then
            multiplied by an estimated
            number of bricks per square
            foot.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-xl font-bold text-orange-600">
              Wall Area = Length × Height
            </p>

            <p className="mt-4 text-xl font-bold text-orange-600">
              Bricks Required = Wall Area
              × 50
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            This calculator uses 50 bricks
            per square foot as a basic
            estimation factor. Actual
            requirements may differ based
            on brick size, mortar thickness,
            wall thickness, openings such
            as doors and windows, and the
            construction method used.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How to Use This Brick
            Calculator
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Follow these steps to estimate
            the number of bricks required
            for a wall.
          </p>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter the wall length.
            </p>

            <p>
              2. Select the length unit in
              feet or meters.
            </p>

            <p>
              3. Enter the wall height.
            </p>

            <p>
              4. Select the height unit in
              feet or meters.
            </p>

            <p>
              5. Click Calculate Bricks to
              see the estimated quantity.
            </p>
          </div>

          <div className="mt-7 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <h3 className="text-2xl font-semibold text-gray-900">
              Unit Conversion
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              If length and height use
              different units, the
              calculator automatically
              converts both measurements to
              feet before calculating wall
              area.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Brick Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Suppose a wall is 20 feet long
            and 10 feet high.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-xl font-bold text-orange-600">
              Wall Area = 20 × 10 = 200
              sq ft
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Bricks Required = 200 × 50
              = 10,000 bricks
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            The 10,000-brick result is a
            basic estimate. For an actual
            construction project, brick
            dimensions, mortar joints,
            openings, and wall thickness
            should be considered before
            ordering materials.
          </p>
        </div>
      </section>

      {/* BRICK ESTIMATION GUIDE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Brick Estimation Guide
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Brick quantity depends on the
            size of the bricks and the
            thickness of the mortar joints.
            Larger bricks generally require
            fewer units per square foot,
            while smaller bricks require
            more.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Doors, windows, vents, and
            other openings reduce the
            actual wall area that needs
            brickwork. For larger projects,
            these openings should be
            measured and deducted from the
            total wall area.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            It is also common to allow
            additional material for
            breakage, cutting, handling,
            and site conditions. The exact
            allowance depends on the
            project and construction
            practices.
          </p>
        </div>
      </section>

      {/* COMMON USES */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Common Uses of a Brick
            Calculator
          </h2>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                House Walls
              </h3>

              <p className="mt-2 text-gray-600">
                Estimate bricks required for
                residential wall construction
                and masonry work.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Boundary Walls
              </h3>

              <p className="mt-2 text-gray-600">
                Calculate a basic brick
                quantity estimate for
                boundary and compound walls.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Building Projects
              </h3>

              <p className="mt-2 text-gray-600">
                Use wall dimensions to
                estimate masonry material
                requirements during project
                planning.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Material Planning
              </h3>

              <p className="mt-2 text-gray-600">
                Get an initial brick quantity
                estimate before discussing
                final material requirements
                with a contractor.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-4xl font-extrabold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-10 space-y-6">
            <div className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm">
              <h3 className="text-2xl font-bold text-gray-900">
                How many bricks are needed
                for 100 sq ft?
              </h3>

              <p className="mt-3 leading-7 text-gray-600">
                Using the basic estimate of
                50 bricks per square foot,
                approximately 5,000 bricks
                would be required for 100
                sq ft. Actual requirements
                can vary with brick size,
                mortar joints, and wall
                construction.
              </p>
            </div>

            <div className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm">
              <h3 className="text-2xl font-bold text-gray-900">
                Does this calculator include
                mortar?
              </h3>

              <p className="mt-3 leading-7 text-gray-600">
                The calculator uses a basic
                brick-per-square-foot
                estimate and does not
                separately calculate mortar
                volume. Mortar thickness can
                affect the final brick
                quantity.
              </p>
            </div>

            <div className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm">
              <h3 className="text-2xl font-bold text-gray-900">
                Can I enter measurements in
                meters?
              </h3>

              <p className="mt-3 leading-7 text-gray-600">
                Yes. You can enter wall
                length and height in meters.
                The calculator converts the
                measurements to feet before
                calculating the estimated
                brick quantity.
              </p>
            </div>

            <div className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm">
              <h3 className="text-2xl font-bold text-gray-900">
                Does wall thickness affect
                brick quantity?
              </h3>

              <p className="mt-3 leading-7 text-gray-600">
                Yes. This calculator provides
                a basic wall-area estimate.
                Different wall thicknesses
                and brick sizes can require
                different quantities of
                bricks.
              </p>
            </div>

            <div className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm">
              <h3 className="text-2xl font-bold text-gray-900">
                Is this brick calculator
                free?
              </h3>

              <p className="mt-3 leading-7 text-gray-600">
                Yes, this brick calculator
                is free to use and does not
                require registration.
              </p>
            </div>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}