"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function BrickCalculatorClient() {
  const [length, setLength] =
    useState("");

  const [height, setHeight] =
    useState("");

  const [lengthUnit, setLengthUnit] =
    useState("ft");

  const [heightUnit, setHeightUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const calculateBricks = () => {
    if (!length || !height)
      return;

    const wallArea =
      parseFloat(length) *
      parseFloat(height);

    const bricksNeeded =
      wallArea * 50;

    setResult(bricksNeeded);
  };

  const resetCalculator = () => {
    setLength("");
    setHeight("");
    setLengthUnit("ft");
    setHeightUnit("ft");
    setResult(null);
  };

  const getAreaUnit = () => {
    if (
      lengthUnit === "m" &&
      heightUnit === "m"
    ) {
      return "sq m";
    }

    return "sq ft";
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Brick Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Wall Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Wall Height: ${height} ${heightUnit}`,
      20,
      50
    );

    doc.text(
      `Estimated Bricks Required: ${result.toFixed(
        0
      )}`,
      20,
      65
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      90
    );

    doc.save(
      "brick-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Brick Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Estimate the number of bricks
            required for wall
            construction, buildings, and
            masonry projects instantly.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Wall Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter wall length"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* HEIGHT */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Wall Height
            </label>

            <input
              type="number"
              min="0"
              value={height}
              onChange={(e) =>
                setHeight(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter wall height"
            />

            <select
              value={heightUnit}
              onChange={(e) =>
                setHeightUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateBricks}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white"
            >
              Calculate Bricks
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Estimated Bricks Needed:{" "}
                {result.toFixed(0)}
              </h2>

              <p className="mt-3 text-gray-600">
                Based on the wall area,
                approximately{" "}
                {result.toFixed(0)} bricks
                are required for your
                construction project.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Brick Calculation Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Brick estimation is commonly
            calculated using wall area
            and standard brick usage per
            square foot or square meter.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Bricks Required = Wall
              Area × 50
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            Actual brick quantity may
            vary depending on mortar
            thickness, brick size, and
            wall type.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Brick
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>
              1. Enter wall length.
            </p>

            <p>
              2. Enter wall height.
            </p>

            <p>
              3. Select the unit type.
            </p>

            <p>
              4. Click calculate to get
              estimated brick quantity.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Brick Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            If the wall length is 20 ft
            and the wall height is 10
            ft:
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Wall Area = 20 × 10 = 200{" "}
              {getAreaUnit()}
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Bricks Required = 200 × 50
              = 10000 bricks
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <h2 className="text-4xl font-extrabold text-gray-900">
          Frequently Asked Questions
        </h2>

        <div className="mt-10 space-y-6">
          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              How many bricks are needed
              for 100 sq ft?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Around 5000 standard
              bricks may be required
              depending on wall
              thickness and brick size.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Does this include mortar?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              This calculator provides a
              basic estimate. Mortar
              thickness may affect actual
              brick quantity.
            </p>
          </div>

          <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6 shadow-xl">
            <h3 className="text-2xl font-bold text-gray-900">
              Is this calculator free?
            </h3>

            <p className="mt-3 leading-7 text-gray-600">
              Yes, all construction
              calculators on CalHub are
              completely free.
            </p>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}