"use client";

import { useState } from "react";
import jsPDF from "jspdf";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function PaintCalculator() {
  const [length, setLength] =
    useState("");

  const [height, setHeight] =
    useState("");

  const [coats, setCoats] =
    useState("1");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [area, setArea] =
    useState<number | null>(null);

  const [areaUnit, setAreaUnit] =
    useState("");

  const convertToFeet = (
    value: number
  ) => {
    switch (unit) {
      case "m":
        return value * 3.28084;

      case "cm":
        return value * 0.0328084;

      case "yd":
        return value * 3;

      default:
        return value;
    }
  };

  const calculatePaint = () => {
    if (
      !length ||
      !height ||
      !coats
    ) {
      return;
    }

    const lengthFt =
      convertToFeet(
        parseFloat(length)
      );

    const heightFt =
      convertToFeet(
        parseFloat(height)
      );

    const wallAreaFt =
      lengthFt * heightFt;

    const paintNeeded =
      (wallAreaFt / 100) *
      parseFloat(coats);

    let finalArea =
      wallAreaFt;

    let finalUnit =
      "sq ft";

    if (unit === "m") {
      finalArea =
        wallAreaFt * 0.092903;

      finalUnit = "m²";
    }

    if (unit === "cm") {
      finalArea =
        wallAreaFt * 929.03;

      finalUnit = "cm²";
    }

    if (unit === "yd") {
      finalArea =
        wallAreaFt / 9;

      finalUnit = "yd²";
    }

    setArea(finalArea);
    setAreaUnit(finalUnit);

    setResult(paintNeeded);
  };

  const resetCalculator = () => {
    setLength("");
    setHeight("");
    setCoats("1");
    setUnit("ft");
    setResult(null);
    setArea(null);
    setAreaUnit("");
  };

  const downloadPDF = () => {
    if (
      result === null ||
      area === null
    ) {
      return;
    }

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Paint Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${unit}`,
      20,
      40
    );

    doc.text(
      `Height: ${height} ${unit}`,
      20,
      50
    );

    doc.text(
      `Number of Coats: ${coats}`,
      20,
      60
    );

    doc.text(
      `Wall Area: ${area.toFixed(
        2
      )} ${areaUnit}`,
      20,
      75
    );

    doc.text(
      `Paint Required: ${result.toFixed(
        2
      )} Liters`,
      20,
      90
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      120
    );

    doc.save(
      "paint-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      <section className="mx-auto max-w-2xl px-6 py-16">

        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Paint Calculator for Walls,
            Rooms & Ceilings
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Estimate paint quantity
            instantly for walls,
            ceilings, rooms, homes,
            and renovation projects.
          </p>
        </div>

        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Unit
            </label>

            <select
              value={unit}
              onChange={(e) =>
                setUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="yd">
                Yard (yd)
              </option>
            </select>
          </div>

          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Wall Length ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculatePaint()
              }
              placeholder="Enter wall length"
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Wall Height ({unit})
            </label>

            <input
              type="number"
              min="0"
              value={height}
              onChange={(e) =>
                setHeight(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculatePaint()
              }
              placeholder="Enter wall height"
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Number of Coats
            </label>

            <input
              type="number"
              min="1"
              value={coats}
              onChange={(e) =>
                setCoats(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculatePaint()
              }
              placeholder="Enter number of coats"
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          <div className="flex gap-4">
            <button
              onClick={
                calculatePaint
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Paint
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>
                    {result !== null &&
            area !== null && (
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">

                <h2 className="text-2xl font-bold text-gray-900">
                  Wall Area:
                  {" "}
                  {area.toFixed(2)}
                  {" "}
                  {areaUnit}
                </h2>

                <h2 className="mt-3 text-2xl font-bold text-gray-900">
                  Paint Required:
                  {" "}
                  {result.toFixed(2)}
                  {" "}
                  Liters
                </h2>

                <p className="mt-3 text-gray-600">
                  Based on the wall
                  dimensions and number
                  of coats selected,
                  the estimated paint
                  requirement is
                  {` ${result.toFixed(
                    2
                  )} liters.`}
                  Actual paint usage
                  may vary depending
                  on paint quality,
                  wall texture, and
                  application method.
                </p>

                <button
                  onClick={
                    downloadPDF
                  }
                  className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
                >
                  Download PDF Report
                </button>

              </div>
            )}

        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Paint Calculation Formula
          </h2>

          <p className="mt-4 text-gray-600">
            Paint quantity depends on
            wall area and the number
            of paint coats applied.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <p className="text-2xl font-semibold text-orange-600">
              Paint Required =
              (Length × Height ÷ 100)
              × Number of Coats
            </p>
          </div>

        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">

          <h2 className="text-3xl font-bold text-gray-900">
            How to Use This Paint
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              1. Select your preferred
              measurement unit.
            </p>

            <p>
              2. Enter wall length.
            </p>

            <p>
              3. Enter wall height.
            </p>

            <p>
              4. Enter the number of
              paint coats required.
            </p>

            <p>
              5. Click Calculate Paint
              to get instant results.
            </p>
          </div>

        </div>
      </section>

      {/* EXAMPLES */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Common Paint Estimation
            Examples
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • 10 ft × 10 ft wall =
              100 sq ft
            </p>

            <p>
              • 12 ft × 15 ft wall =
              180 sq ft
            </p>

            <p>
              • Two coats on 200 sq ft
              wall ≈ 4 liters paint
            </p>

            <p>
              • Three coats on 300 sq ft
              wall ≈ 9 liters paint
            </p>
          </div>

        </div>
      </section>

      {/* WHY USE */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Paint
            Calculator?
          </h2>

          <p className="mt-4 text-gray-600">
            This calculator helps
            homeowners, contractors,
            painters, and builders
            estimate paint quantity
            accurately before
            purchasing materials.
          </p>

          <p className="mt-4 text-gray-600">
            Proper paint estimation
            reduces waste, controls
            project costs, and helps
            improve planning.
          </p>

        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                How much paint do I
                need for a room?
              </h3>

              <p className="mt-2 text-gray-600">
                Paint requirements
                depend on wall area,
                paint coverage, and
                the number of coats.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I calculate
                ceiling paint?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. This calculator
                can be used for walls,
                ceilings, and interior
                painting projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator
                free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. All calculators
                on CalHub are free to
                use.
              </p>
            </div>

          </div>

        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}