"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function DrywallCalculatorClient() {
  const [wallLength, setWallLength] =
    useState("");

  const [wallHeight, setWallHeight] =
    useState("");

  const [sheetArea, setSheetArea] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [totalArea, setTotalArea] =
    useState<number | null>(null);

  const calculateDrywall = () => {
    if (
      !wallLength ||
      !wallHeight ||
      !sheetArea
    )
      return;

    const length =
      parseFloat(wallLength);

    const height =
      parseFloat(wallHeight);

    const sheet =
      parseFloat(sheetArea);

    if (
      isNaN(length) ||
      isNaN(height) ||
      isNaN(sheet) ||
      length <= 0 ||
      height <= 0 ||
      sheet <= 0
    ) {
      return;
    }

    const wallArea =
      length * height;

    const sheetsNeeded =
      Math.ceil(
        wallArea / sheet
      );

    setTotalArea(wallArea);

    setResult(sheetsNeeded);
  };

  const resetCalculator = () => {
    setWallLength("");
    setWallHeight("");
    setSheetArea("");
    setUnit("ft");
    setResult(null);
    setTotalArea(null);
  };

  const downloadPDF = () => {
    if (
      result === null ||
      totalArea === null
    )
      return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Drywall Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Wall Length: ${wallLength} ${unit}`,
      20,
      40
    );

    doc.text(
      `Wall Height: ${wallHeight} ${unit}`,
      20,
      50
    );

    doc.text(
      `Sheet Area: ${sheetArea} sq ${unit}`,
      20,
      60
    );

    doc.text(
      `Wall Area: ${totalArea.toFixed(
        2
      )} sq ${unit}`,
      20,
      75
    );

    doc.text(
      `Drywall Sheets Required: ${result}`,
      20,
      85
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      110
    );

    doc.save(
      "drywall-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Drywall Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate drywall sheets
            required for walls,
            ceilings, remodeling,
            and construction projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
        {/* WALL LENGTH */}
<div className="mb-5">
  <label className="mb-2 block font-medium text-gray-700">
    Wall Length
  </label>

  <input
    type="number"
    min="0"
    value={wallLength}
    onChange={(e) =>
      setWallLength(
        e.target.value
      )
    }
    onKeyDown={(e) =>
      e.key === "Enter" &&
      calculateDrywall()
    }
    className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
    placeholder="e.g. 20"
  />

  <select
    value={unit}
    onChange={(e) =>
      setUnit(
        e.target.value
      )
    }
    className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
  >
    <option value="ft">
      Feet (ft)
    </option>

    <option value="m">
      Meter (m)
    </option>
  </select>
</div>

{/* WALL HEIGHT */}
<div className="mb-5">
  <label className="mb-2 block font-medium text-gray-700">
    Wall Height
  </label>

  <input
    type="number"
    min="0"
    value={wallHeight}
    onChange={(e) =>
      setWallHeight(
        e.target.value
      )
    }
    onKeyDown={(e) =>
      e.key === "Enter" &&
      calculateDrywall()
    }
    className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
    placeholder="e.g. 10"
  />
</div>

{/* SHEET AREA */}
<div className="mb-6">
  <label className="mb-2 block font-medium text-gray-700">
    Drywall Sheet Area
  </label>

  <input
    type="number"
    min="0"
    value={sheetArea}
    onChange={(e) =>
      setSheetArea(
        e.target.value
      )
    }
    onKeyDown={(e) =>
      e.key === "Enter" &&
      calculateDrywall()
    }
    className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
    placeholder={`e.g. ${
      unit === "ft"
        ? "32"
        : "2.97"
    }`}
  />

  <p className="mt-2 text-sm text-gray-500">
    Example: Standard 4×8 drywall
    sheet = 32 sq ft
  </p>
</div>

{/* BUTTONS */}
<div className="flex gap-4">
  <button
    onClick={
      calculateDrywall
    }
    className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
  >
    Calculate Drywall
  </button>

  <button
    onClick={
      resetCalculator
    }
    className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
  >
    Reset
  </button>
</div>

{/* RESULT */}
{result !== null &&
  totalArea !== null && (
    <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
      <h2 className="text-2xl font-bold text-gray-900">
        Drywall Sheets Needed:{" "}
        {result}
      </h2>

      <p className="mt-3 text-gray-600">
        Total Wall Area:{" "}
        {totalArea.toFixed(
          2
        )}{" "}
        sq {unit}
      </p>

      <p className="mt-2 text-gray-600">
        Estimated drywall sheets
        required for your wall or
        ceiling project.
      </p>

      <button
        onClick={
          downloadPDF
        }
        className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
      >
        Download PDF Report
      </button>
    </div>
  )}
</div>
</section>
      {/* FORMULA */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Drywall Calculation Formula
          </h2>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Drywall sheets are estimated by
            dividing the total wall area by
            the coverage area of one drywall
            sheet.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              Drywall Sheets = Wall Area ÷
              Sheet Area
            </p>
          </div>

          <p className="mt-6 leading-8 text-gray-600">
            Always round the result up to
            the next whole sheet because
            drywall cannot be purchased in
            fractions.
          </p>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How To Use This Drywall
            Calculator
          </h2>

          <div className="mt-6 space-y-4 text-lg text-gray-600">
            <p>1. Enter wall length.</p>

            <p>2. Enter wall height.</p>

            <p>
              3. Enter the drywall sheet
              coverage area.
            </p>

            <p>
              4. Click Calculate to estimate
              the required drywall sheets.
            </p>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Example Calculation
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            A wall measuring 20 ft × 10 ft
            has an area of 200 sq ft.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-6">
            <p className="text-2xl font-bold text-orange-600">
              200 ÷ 32 = 6.25
            </p>

            <p className="mt-4 text-xl font-semibold text-gray-700">
              Required Drywall Sheets = 7
            </p>
          </div>
        </div>
      </section>

      {/* STANDARD DRYWALL SIZES */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Standard Drywall Sheet Sizes
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>• 4 × 8 ft = 32 sq ft</p>

            <p>• 4 × 10 ft = 40 sq ft</p>

            <p>• 4 × 12 ft = 48 sq ft</p>

            <p>• 4 × 16 ft = 64 sq ft</p>
          </div>
        </div>
      </section>

      {/* WHY USE */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Drywall
            Calculator?
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            This calculator helps
            contractors, builders,
            homeowners, and remodelers
            estimate drywall sheets quickly
            for walls and ceilings.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Accurate estimation reduces
            material waste and helps improve
            project planning and budgeting.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-5xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">
            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What does a drywall
                calculator do?
              </h3>

              <p className="mt-2 text-gray-600">
                It estimates how many
                drywall sheets are required
                based on wall dimensions.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Does this include waste?
              </h3>

              <p className="mt-2 text-gray-600">
                No. Consider purchasing
                5–10% extra drywall to allow
                for cuts and waste.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. All CalHub calculators
                are completely free to use.
              </p>
            </div>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}