"use client";

import { useState } from "react";
import jsPDF from "jspdf";

export default function DrywallCalculatorClient() {
  const [wallLength, setWallLength] =
    useState("");

  const [wallHeight, setWallHeight] =
    useState("");

  const [sheetArea, setSheetArea] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [totalArea, setTotalArea] =
    useState<number | null>(null);

  const calculateDrywall = () => {
    if (
      !wallLength ||
      !wallHeight ||
      !sheetArea
    ) {
      return;
    }

    const length =
      parseFloat(wallLength);

    const height =
      parseFloat(wallHeight);

    const sheet =
      parseFloat(sheetArea);

    const wallArea =
      length * height;

    const sheetsNeeded =
      wallArea / sheet;

    setTotalArea(wallArea);

    setResult(
      Math.ceil(sheetsNeeded)
    );
  };

  const resetCalculator = () => {
    setWallLength("");
    setWallHeight("");
    setSheetArea("");
    setUnit("ft");
    setResult(null);
    setTotalArea(null);
  };

  const downloadPDF = () => {
    if (
      result === null ||
      totalArea === null
    )
      return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Drywall Calculator Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Wall Length: ${wallLength} ${unit}`,
      20,
      40
    );

    doc.text(
      `Wall Height: ${wallHeight} ${unit}`,
      20,
      50
    );

    doc.text(
      `Drywall Sheet Area: ${sheetArea} sq ${unit}`,
      20,
      60
    );

    doc.text(
      `Total Wall Area: ${totalArea.toFixed(
        2
      )} sq ${unit}`,
      20,
      80
    );

    doc.text(
      `Drywall Sheets Needed: ${result}`,
      20,
      90
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      120
    );

    doc.save(
      "drywall-calculator-report.pdf"
    );
  };

  return (
    <div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
      {/* WALL LENGTH */}
      <div className="mb-4">
        <label className="mb-2 block text-sm font-medium text-gray-700">
          Wall Length
        </label>

        <input
          type="number"
          min="0"
          value={wallLength}
          onChange={(e) =>
            setWallLength(
              e.target.value
            )
          }
          placeholder="Enter wall length"
          className="w-full rounded-xl border border-orange-200 bg-white px-4 py-3 text-black outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200"
        />
      </div>

      {/* WALL HEIGHT */}
      <div className="mb-4">
        <label className="mb-2 block text-sm font-medium text-gray-700">
          Wall Height
        </label>

        <input
          type="number"
          min="0"
          value={wallHeight}
          onChange={(e) =>
            setWallHeight(
              e.target.value
            )
          }
          placeholder="Enter wall height"
          className="w-full rounded-xl border border-orange-200 bg-white px-4 py-3 text-black outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200"
        />
      </div>

      {/* UNIT */}
      <div className="mb-4">
        <label className="mb-2 block text-sm font-medium text-gray-700">
          Measurement Unit
        </label>

        <select
          value={unit}
          onChange={(e) =>
            setUnit(e.target.value)
          }
          className="w-full rounded-xl border border-orange-200 bg-white px-4 py-3 text-black outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200"
        >
          <option value="ft">
            Feet (ft)
          </option>

          <option value="m">
            Meter (m)
          </option>
        </select>
      </div>

      {/* SHEET AREA */}
      <div className="mb-6">
        <label className="mb-2 block text-sm font-medium text-gray-700">
          Drywall Sheet Area (sq{" "}
          {unit})
        </label>

        <input
          type="number"
          min="0"
          value={sheetArea}
          onChange={(e) =>
            setSheetArea(
              e.target.value
            )
          }
          placeholder="Enter drywall sheet area"
          className="w-full rounded-xl border border-orange-200 bg-white px-4 py-3 text-black outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-200"
        />
      </div>

      {/* BUTTONS */}
      <div className="flex gap-4">
        <button
          onClick={calculateDrywall}
          className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
        >
          Calculate
        </button>

        <button
          onClick={resetCalculator}
          className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700"
        >
          Reset
        </button>
      </div>

      {/* RESULT */}
      {result !== null &&
        totalArea !== null && (
          <div className="mt-6 rounded-2xl bg-orange-50 p-5 shadow-inner">
            <h2 className="text-2xl font-bold text-black">
              Drywall Sheets
              Needed: {result}
            </h2>

            <p className="mt-3 text-gray-700">
              Total Wall Area:{" "}
              {totalArea.toFixed(2)} sq{" "}
              {unit}
            </p>

            <button
              onClick={downloadPDF}
              className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
            >
              Download PDF Report
            </button>
          </div>
        )}
    </div>
  );
}