"use client";

import { useState } from "react";
import jsPDF from "jspdf";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function TileCalculatorClient() {
  const [floorLength, setFloorLength] =
    useState("");

  const [floorWidth, setFloorWidth] =
    useState("");

  const [tileLength, setTileLength] =
    useState("");

  const [tileWidth, setTileWidth] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [extraTiles, setExtraTiles] =
    useState<number | null>(null);

  const calculateTiles = () => {
    if (
      !floorLength ||
      !floorWidth ||
      !tileLength ||
      !tileWidth
    ) {
      return;
    }

    const floorArea =
      parseFloat(floorLength) *
      parseFloat(floorWidth);

    const tileArea =
      parseFloat(tileLength) *
      parseFloat(tileWidth);

    const tilesNeeded =
      floorArea / tileArea;

    setResult(Math.ceil(tilesNeeded));

    setExtraTiles(
      Math.ceil(tilesNeeded * 1.1)
    );
  };

  const resetCalculator = () => {
    setFloorLength("");
    setFloorWidth("");
    setTileLength("");
    setTileWidth("");
    setUnit("ft");
    setResult(null);
    setExtraTiles(null);
  };

  const downloadPDF = () => {
    if (
      result === null ||
      extraTiles === null
    )
      return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Tile Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Floor Length: ${floorLength} ${unit}`,
      20,
      40
    );

    doc.text(
      `Floor Width: ${floorWidth} ${unit}`,
      20,
      50
    );

    doc.text(
      `Tile Length: ${tileLength} ${unit}`,
      20,
      60
    );

    doc.text(
      `Tile Width: ${tileWidth} ${unit}`,
      20,
      70
    );

    doc.text(
      `Tiles Needed: ${result}`,
      20,
      90
    );

    doc.text(
      `Recommended With 10% Extra: ${extraTiles}`,
      20,
      100
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      130
    );

    doc.save(
      "tile-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO SECTION */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Tile Calculator for
            Flooring, Walls &
            Construction
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate the exact number
            of tiles needed for floors,
            kitchens, bathrooms, walls,
            patios, and construction
            projects with ease.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          {/* UNIT */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Select Unit
            </label>

            <select
              value={unit}
              onChange={(e) =>
                setUnit(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* FLOOR LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Floor Length ({unit})
            </label>

            <input
              type="number"
              step="any"
              min="0"
              value={floorLength}
              onChange={(e) =>
                setFloorLength(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateTiles()
              }
              placeholder="Enter floor length"
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* FLOOR WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Floor Width ({unit})
            </label>

            <input
              type="number"
              step="any"
              min="0"
              value={floorWidth}
              onChange={(e) =>
                setFloorWidth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateTiles()
              }
              placeholder="Enter floor width"
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* TILE LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Tile Length ({unit})
            </label>

            <input
              type="number"
              step="any"
              min="0"
              value={tileLength}
              onChange={(e) =>
                setTileLength(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateTiles()
              }
              placeholder="Enter tile length"
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* TILE WIDTH */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Tile Width ({unit})
            </label>

            <input
              type="number"
              step="any"
              min="0"
              value={tileWidth}
              onChange={(e) =>
                setTileWidth(
                  e.target.value
                )
              }
              onKeyDown={(e) =>
                e.key === "Enter" &&
                calculateTiles()
              }
              placeholder="Enter tile width"
              className="w-full rounded-2xl border border-orange-200 p-4 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            />
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={
                calculateTiles
              }
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Tiles
            </button>

            <button
              onClick={
                resetCalculator
              }
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null &&
            extraTiles !== null && (
              <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
                <h2 className="text-2xl font-bold text-gray-900">
                  Tiles Needed:
                  {" "}
                  {result}
                </h2>

                <p className="mt-3 text-lg text-gray-700">
                  Recommended With
                  10% Extra:
                  {" "}
                  {extraTiles}
                </p>

                <p className="mt-4 text-gray-600">
                  Adding extra tiles
                  helps cover cutting,
                  breakage, future
                  repairs, and waste
                  during installation.
                </p>

                <button
                  onClick={
                    downloadPDF
                  }
                  className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
                >
                  Download PDF
                  Report
                </button>
              </div>
            )}
        </div>
      </section>

            {/* FORMULA */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Tile Calculation Formula
          </h2>

          <p className="mt-4 text-gray-600">
            Tile quantity is calculated by
            dividing the total floor area
            by the area of a single tile.
            This helps estimate flooring,
            wall tiling, bathroom
            installations, kitchens, and
            construction projects.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Formula
            </h3>

            <p className="mt-3 text-lg font-medium text-orange-600">
              Tiles Needed =
              Floor Area ÷ Tile Area
            </p>
          </div>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            How to Use This Tile
            Calculator
          </h2>

          <p className="mt-4 text-gray-600">
            Enter the floor length and
            width, then enter the tile
            dimensions. Click the
            calculate button to instantly
            find how many tiles are needed
            for your project.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Example Calculation
            </h3>

            <p className="mt-3 text-gray-600">
              Floor Area = 20 × 15 = 300
            </p>

            <p className="mt-3 text-gray-600">
              Tile Area = 2 × 2 = 4
            </p>

            <p className="mt-3 font-medium text-orange-600">
              Tiles Needed = 300 ÷ 4 = 75
            </p>
          </div>
        </div>
      </section>

      {/* COMMON EXAMPLES */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Common Tile Calculation
            Examples
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • 100 sq ft area with
              1×1 ft tile = 100 tiles
            </p>

            <p>
              • 300 sq ft area with
              2×2 ft tile = 75 tiles
            </p>

            <p>
              • 500 sq ft area with
              1×2 ft tile = 250 tiles
            </p>

            <p>
              • Add 10% extra tiles for
              wastage and future repairs
            </p>
          </div>
        </div>
      </section>

      {/* TILE SIZE GUIDE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Common Tile Sizes
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>• 12 × 12 inch tiles</p>

            <p>• 12 × 24 inch tiles</p>

            <p>• 24 × 24 inch tiles</p>

            <p>• 24 × 48 inch tiles</p>

            <p>
              • Large format porcelain
              tiles
            </p>
          </div>
        </div>
      </section>

      {/* WHY USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Tile
            Calculator?
          </h2>

          <p className="mt-4 text-gray-600">
            This tile calculator helps
            contractors, homeowners,
            builders, architects, and
            interior designers estimate
            tile requirements quickly and
            accurately.
          </p>

          <p className="mt-4 text-gray-600">
            Proper tile estimation helps
            reduce material waste, control
            project costs, and avoid
            purchasing too many or too few
            tiles.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What is a tile calculator?
              </h3>

              <p className="mt-2 text-gray-600">
                A tile calculator helps
                estimate the number of
                tiles required for floors,
                walls, kitchens, bathrooms,
                and construction projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Why should I buy extra
                tiles?
              </h3>

              <p className="mt-2 text-gray-600">
                Extra tiles help cover
                cutting waste, accidental
                breakage, and future
                repairs.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I calculate wall
                tiles?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. This calculator can
                be used for both floor and
                wall tile calculations.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. All calculators on
                CalHub are completely free
                to use.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                How accurate is this tile
                calculator?
              </h3>

              <p className="mt-2 text-gray-600">
                It provides accurate tile
                estimates based on the
                dimensions entered. Adding
                10% extra tiles is
                recommended for real-world
                projects.
              </p>
            </div>

          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}