"use client";

import { useState } from "react";
import jsPDF from "jspdf";

export default function PlasterCalculatorClient() {
  const [length, setLength] =
    useState("");

  const [height, setHeight] =
    useState("");

  const [thickness, setThickness] =
    useState("");

  const [unit, setUnit] =
    useState("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const calculatePlaster = () => {
    if (
      !length ||
      !height ||
      !thickness
    ) {
      return;
    }

    let wallLength =
      parseFloat(length);

    let wallHeight =
      parseFloat(height);

    if (unit === "m") {
      wallLength *= 3.28084;
      wallHeight *= 3.28084;
    }

    const volume =
      wallLength *
      wallHeight *
      (parseFloat(thickness) / 12);

    setResult(volume);
  };

  const resetCalculator = () => {
    setLength("");
    setHeight("");
    setThickness("");
    setResult(null);
    setUnit("ft");
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Plaster Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Wall Length: ${length} ${unit}`,
      20,
      40
    );

    doc.text(
      `Wall Height: ${height} ${unit}`,
      20,
      50
    );

    doc.text(
      `Thickness: ${thickness} inch`,
      20,
      60
    );

    doc.text(
      `Plaster Volume: ${result.toFixed(
        2
      )} ft³`,
      20,
      80
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      110
    );

    doc.save(
      "plaster-calculation-report.pdf"
    );
  };

  return (
    <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">

      {/* UNIT */}
      <div className="mb-5">
        <label className="mb-2 block font-medium text-gray-700">
          Unit
        </label>

        <select
          value={unit}
          onChange={(e) =>
            setUnit(e.target.value)
          }
          className="w-full rounded-2xl border border-orange-200 p-3 outline-none focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
        >
          <option value="ft">
            Feet (ft)
          </option>

          <option value="m">
            Meter (m)
          </option>
        </select>
      </div>

      {/* LENGTH */}
      <div className="mb-5">
        <label className="mb-2 block font-medium text-gray-700">
          Wall Length ({unit})
        </label>

        <input
          type="number"
          min="0"
          value={length}
          onChange={(e) =>
            setLength(e.target.value)
          }
          onKeyDown={(e) =>
            e.key === "Enter" &&
            calculatePlaster()
          }
          placeholder="Enter wall length"
          className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
        />
      </div>

      {/* HEIGHT */}
      <div className="mb-5">
        <label className="mb-2 block font-medium text-gray-700">
          Wall Height ({unit})
        </label>

        <input
          type="number"
          min="0"
          value={height}
          onChange={(e) =>
            setHeight(e.target.value)
          }
          onKeyDown={(e) =>
            e.key === "Enter" &&
            calculatePlaster()
          }
          placeholder="Enter wall height"
          className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
        />
      </div>

      {/* THICKNESS */}
      <div className="mb-6">
        <label className="mb-2 block font-medium text-gray-700">
          Thickness (inch)
        </label>

        <input
          type="number"
          min="0"
          value={thickness}
          onChange={(e) =>
            setThickness(
              e.target.value
            )
          }
          onKeyDown={(e) =>
            e.key === "Enter" &&
            calculatePlaster()
          }
          placeholder="Enter thickness"
          className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
        />
      </div>

      {/* BUTTONS */}
      <div className="flex gap-4">
        <button
          onClick={calculatePlaster}
          className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
        >
          Calculate Plaster
        </button>

        <button
          onClick={resetCalculator}
          className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
        >
          Reset
        </button>
      </div>
            {/* RESULT */}
      {result !== null && (
        <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">

          <h2 className="text-2xl font-bold text-gray-900">
            Plaster Volume:
            {" "}
            {result.toFixed(2)} ft³
          </h2>

          <p className="mt-3 text-gray-600">
            The estimated plaster volume is
            {` ${result.toFixed(2)} ft³ `}
            based on the wall dimensions and
            plaster thickness entered. This
            value can be used to estimate
            cement, sand, and plaster
            material requirements for wall
            and ceiling finishing work.
          </p>

          <button
            onClick={downloadPDF}
            className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
          >
            Download PDF Report
          </button>

        </div>
      )}
    </div>
  );
}