"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

type Unit = "ft" | "m" | "cm" | "inch";

export default function AreaCalculatorClient() {
  const [length, setLength] = useState("");
  const [width, setWidth] = useState("");

  const [lengthUnit, setLengthUnit] =
    useState<Unit>("ft");

  const [widthUnit, setWidthUnit] =
    useState<Unit>("ft");

  const [result, setResult] =
    useState<number | null>(null);

  const [resultUnit, setResultUnit] =
    useState("sq ft");

  const convertToFeet = (
    value: number,
    unit: Unit
  ) => {
    switch (unit) {
      case "m":
        return value * 3.280839895;

      case "cm":
        return value * 0.03280839895;

      case "inch":
        return value / 12;

      default:
        return value;
    }
  };

  const calculateArea = () => {
    if (!length || !width) return;

    const lengthValue = parseFloat(length);
    const widthValue = parseFloat(width);

    if (
      isNaN(lengthValue) ||
      isNaN(widthValue) ||
      lengthValue <= 0 ||
      widthValue <= 0
    ) {
      return;
    }

    const lengthInFeet =
      convertToFeet(
        lengthValue,
        lengthUnit
      );

    const widthInFeet =
      convertToFeet(
        widthValue,
        widthUnit
      );

    const area =
      lengthInFeet * widthInFeet;

    setResult(area);
    setResultUnit("sq ft");
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setLengthUnit("ft");
    setWidthUnit("ft");
    setResult(null);
    setResultUnit("sq ft");
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Area Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Total Area: ${result.toFixed(
        2
      )} ${resultUnit}`,
      20,
      60
    );

    doc.text(
      "Formula: Area = Length × Width",
      20,
      75
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      95
    );

    doc.save(
      "area-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO SECTION */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Area Calculator for Rooms,
            Flooring & Construction
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Calculate area instantly for
            rooms, flooring, plots, land,
            paint estimation, and
            construction projects.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateArea();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 20"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(
                  e.target.value as Unit
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="inch">
                Inch (in)
              </option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={width}
              onChange={(e) =>
                setWidth(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateArea();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="e.g. 15"
            />

            <select
              value={widthUnit}
              onChange={(e) =>
                setWidthUnit(
                  e.target.value as Unit
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>

              <option value="cm">
                Centimeter (cm)
              </option>

              <option value="inch">
                Inch (in)
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateArea}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02]"
            >
              Calculate Area
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition-all duration-300 hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Total Area:{" "}
                {result.toFixed(2)}{" "}
                {resultUnit}
              </h2>

              <p className="mt-3 text-gray-600">
                The calculated area is{" "}
                {result.toFixed(2)}{" "}
                square feet. The
                calculator converts both
                measurements to feet before
                calculating the final area.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Area Calculation Formula
          </h2>

          <p className="mt-4 text-gray-600">
            Area is calculated by
            multiplying length by width.
            For accurate results, both
            measurements must represent
            the same unit before
            multiplication.
          </p>

          <p className="mt-4 text-gray-600">
            This calculator automatically
            converts feet, meters,
            centimeters, and inches into
            feet before calculating the
            final square-foot area.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Formula
            </h3>

            <p className="mt-3 text-lg font-medium text-orange-600">
              Area = Length × Width
            </p>
          </div>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How to Use This Area
            Calculator
          </h2>

          <p className="mt-4 text-gray-600">
            Enter the length and width,
            select the correct unit for
            each measurement, and click
            Calculate Area. The calculator
            converts the measurements and
            displays the final area in
            square feet.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Example Calculation
            </h3>

            <p className="mt-3 text-gray-600">
              If the length is 20 ft and
              the width is 15 ft:
            </p>

            <p className="mt-3 font-medium text-orange-600">
              Area = 20 × 15 = 300 sq ft
            </p>
          </div>

          <div className="mt-5 rounded-2xl border border-orange-100 bg-white p-5">
            <h3 className="text-xl font-semibold text-gray-900">
              Mixed Unit Example
            </h3>

            <p className="mt-3 text-gray-600">
              If the length is 6 meters
              and the width is 10 ft, the
              calculator converts 6 meters
              into feet before multiplying
              the measurements.
            </p>
          </div>
        </div>
      </section>

      {/* COMMON EXAMPLES */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Common Area Calculation
            Examples
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • 10 × 10 room = 100 sq ft
            </p>

            <p>
              • 12 × 15 bedroom = 180 sq
              ft
            </p>

            <p>
              • 20 × 30 plot = 600 sq ft
            </p>

            <p>
              • 25 × 40 flooring area =
              1000 sq ft
            </p>

            <p>
              • 30 × 50 construction area
              = 1500 sq ft
            </p>
          </div>
        </div>
      </section>

      {/* CONVERSION GUIDE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Square Foot Conversion Guide
          </h2>

          <p className="mt-4 text-gray-600">
            Understanding area unit
            conversions is useful when
            working with construction
            drawings, property measurements,
            flooring estimates, and land
            calculations.
          </p>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              • 1 square foot = 0.0929
              square meters
            </p>

            <p>
              • 1 square meter = 10.7639
              square feet
            </p>

            <p>
              • 1 square yard = 9 square
              feet
            </p>

            <p>
              • 1 acre = 43,560 square
              feet
            </p>
          </div>
        </div>
      </section>

      {/* WHY USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Why Use This Area
            Calculator?
          </h2>

          <p className="mt-4 text-gray-600">
            This area calculator helps
            contractors, builders,
            homeowners, architects, and
            engineers quickly estimate
            room size, flooring area,
            paint coverage, and
            construction material
            requirements.
          </p>

          <p className="mt-4 text-gray-600">
            Accurate area calculation is
            important before purchasing
            tiles, flooring materials,
            paint, concrete, and other
            construction supplies.
          </p>

          <p className="mt-4 text-gray-600">
            The calculator also supports
            different measurement units,
            making it useful for projects
            where dimensions are provided
            in feet, meters, centimeters,
            or inches.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl transition-all duration-300 hover:shadow-2xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">
            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What is an area
                calculator?
              </h3>

              <p className="mt-2 text-gray-600">
                An area calculator helps
                measure the total surface
                area of a room, floor,
                plot, or construction
                space using its length and
                width.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I calculate room area?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. Enter the room length
                and width, select the
                appropriate units, and the
                calculator will calculate
                the room area.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I use different units
                for length and width?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes. You can select
                different units for the
                length and width. The
                calculator converts both
                measurements to feet before
                calculating the area.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes, this area calculator
                is free to use and does not
                require registration.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Why is area calculation
                important in construction?
              </h3>

              <p className="mt-2 text-gray-600">
                Area calculation helps
                estimate flooring, concrete,
                paint, tiles, and other
                construction material
                requirements.
              </p>
            </div>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}