import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-gray-100">
      <Navbar />

      <section className="mx-auto max-w-5xl px-6 py-20">
        <div className="rounded-3xl bg-white p-10 shadow-xl">
          <h1 className="text-5xl font-extrabold text-black">
            Disclaimer
          </h1>

          <p className="mt-8 text-lg leading-8 text-gray-600">
            The information and calculators
            provided on Calculator Hub are for
            general informational and estimation
            purposes only.
          </p>

          <h2 className="mt-10 text-3xl font-bold text-black">
            No Professional Advice
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Results generated by our calculators
            should not be considered professional
            engineering or construction advice.
          </p>

          <h2 className="mt-10 text-3xl font-bold text-black">
            Accuracy
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            While we strive for accuracy, we do
            not guarantee that all calculations
            are error-free or suitable for every
            project.
          </p>

          <h2 className="mt-10 text-3xl font-bold text-black">
            Use at Your Own Risk
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Users are responsible for verifying
            all calculations before applying them
            in actual construction projects.
          </p>
        </div>
      </section>

      <Footer />
    </main>
  );
}