"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

const ASPHALT_DENSITY_KG_M3 = 2323;
const KG_PER_US_TON = 907.18474;

export default function AsphaltCalculatorClient() {
  const [length, setLength] = useState("");
  const [width, setWidth] = useState("");
  const [thickness, setThickness] = useState("");

  const [lengthUnit, setLengthUnit] = useState("ft");
  const [widthUnit, setWidthUnit] = useState("ft");
  const [thicknessUnit, setThicknessUnit] = useState("inch");

  const [result, setResult] = useState<{
    areaSqFt: number;
    areaSqM: number;
    volumeCuFt: number;
    volumeCuM: number;
    weightKg: number;
    weightTons: number;
  } | null>(null);

  const [error, setError] = useState("");

  const convertLengthToMeters = (
    value: number,
    unit: string
  ) => {
    switch (unit) {
      case "m":
        return value;
      case "cm":
        return value / 100;
      case "inch":
        return value * 0.0254;
      case "ft":
      default:
        return value * 0.3048;
    }
  };

  const calculateAsphalt = () => {
    setError("");

    const lengthValue = parseFloat(length);
    const widthValue = parseFloat(width);
    const thicknessValue = parseFloat(thickness);

    if (
      !length ||
      !width ||
      !thickness ||
      Number.isNaN(lengthValue) ||
      Number.isNaN(widthValue) ||
      Number.isNaN(thicknessValue)
    ) {
      setError("Please enter valid values for all three measurements.");
      return;
    }

    if (
      lengthValue <= 0 ||
      widthValue <= 0 ||
      thicknessValue <= 0
    ) {
      setError("All measurements must be greater than zero.");
      return;
    }

    const lengthMeters = convertLengthToMeters(
      lengthValue,
      lengthUnit
    );

    const widthMeters = convertLengthToMeters(
      widthValue,
      widthUnit
    );

    const thicknessMeters = convertLengthToMeters(
      thicknessValue,
      thicknessUnit
    );

    const areaSqM =
      lengthMeters * widthMeters;

    const volumeCuM =
      areaSqM * thicknessMeters;

    const areaSqFt =
      areaSqM * 10.7639104167;

    const volumeCuFt =
      volumeCuM * 35.3146667215;

    const weightKg =
      volumeCuM * ASPHALT_DENSITY_KG_M3;

    const weightTons =
      weightKg / KG_PER_US_TON;

    setResult({
      areaSqFt,
      areaSqM,
      volumeCuFt,
      volumeCuM,
      weightKg,
      weightTons,
    });
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setThickness("");
    setLengthUnit("ft");
    setWidthUnit("ft");
    setThicknessUnit("inch");
    setResult(null);
    setError("");
  };

  const downloadPDF = () => {
    if (!result) return;

    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("Asphalt Calculation Report", 20, 20);

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Thickness: ${thickness} ${thicknessUnit}`,
      20,
      60
    );

    doc.text(
      `Area: ${result.areaSqFt.toFixed(2)} sq ft`,
      20,
      75
    );

    doc.text(
      `Volume: ${result.volumeCuFt.toFixed(2)} cubic ft`,
      20,
      85
    );

    doc.text(
      `Volume: ${result.volumeCuM.toFixed(2)} cubic m`,
      20,
      95
    );

    doc.text(
      `Estimated Asphalt Weight: ${result.weightKg.toFixed(
        0
      )} kg`,
      20,
      105
    );

    doc.text(
      `Estimated Asphalt Weight: ${result.weightTons.toFixed(
        2
      )} US tons`,
      20,
      115
    );

    doc.setFontSize(10);

    doc.text(
      "Weight estimate uses an assumed asphalt density of 2,323 kg/m³.",
      20,
      135
    );

    doc.text(
      "Actual asphalt density may vary by mix and project conditions.",
      20,
      143
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      160
    );

    doc.save(
      "asphalt-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-3xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Asphalt Calculator
          </h1>

          <p className="mt-4 text-lg leading-8 text-gray-600">
            Calculate asphalt area, volume,
            and estimated weight for roads,
            driveways, parking lots,
            pathways, and paving projects.
            Enter your project dimensions
            and get a detailed estimate
            instantly.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-2xl font-bold text-gray-900">
            Calculate Asphalt Quantity
          </h2>

          <p className="mt-2 text-gray-600">
            Enter the length, width, and
            pavement thickness below.
          </p>

          {/* LENGTH */}
          <div className="mt-7">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateAsphalt();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter length"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(e.target.value)
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mt-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={width}
              onChange={(e) =>
                setWidth(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateAsphalt();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter width"
            />

            <select
              value={widthUnit}
              onChange={(e) =>
                setWidthUnit(e.target.value)
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* THICKNESS */}
          <div className="mt-5">
            <label className="mb-2 block font-medium text-gray-700">
              Asphalt Thickness
            </label>

            <input
              type="number"
              min="0"
              step="any"
              value={thickness}
              onChange={(e) =>
                setThickness(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  calculateAsphalt();
                }
              }}
              className="w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
              placeholder="Enter thickness"
            />

            <select
              value={thicknessUnit}
              onChange={(e) =>
                setThicknessUnit(e.target.value)
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 bg-white p-3 outline-none transition focus:border-orange-500 focus:ring-4 focus:ring-orange-100"
            >
              <option value="inch">
                Inches (in)
              </option>

              <option value="ft">
                Feet (ft)
              </option>

              <option value="cm">
                Centimeters (cm)
              </option>

              <option value="m">
                Meters (m)
              </option>
            </select>
          </div>

          {/* DENSITY NOTE */}
          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="font-semibold text-gray-900">
              Asphalt Weight Assumption
            </h3>

            <p className="mt-2 text-sm leading-6 text-gray-600">
              The weight estimate uses an
              assumed asphalt density of
              approximately 2,323 kg/m³.
              Actual density can vary
              depending on the asphalt mix,
              aggregate, compaction, and
              project specifications.
            </p>
          </div>

          {error && (
            <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">
              {error}
            </div>
          )}

          {/* BUTTONS */}
          <div className="mt-6 flex flex-col gap-4 sm:flex-row">
            <button
              onClick={calculateAsphalt}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white transition-all duration-300 hover:scale-[1.02] hover:from-orange-600 hover:to-amber-600"
            >
              Calculate Asphalt
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700 transition hover:bg-orange-50"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-7 rounded-3xl bg-white p-6 shadow-lg">
              <h2 className="text-2xl font-bold text-gray-900">
                Asphalt Estimate
              </h2>

              <div className="mt-5 grid gap-4 sm:grid-cols-2">
                <div className="rounded-2xl bg-orange-50 p-5">
                  <p className="text-sm text-gray-500">
                    Paving Area
                  </p>

                  <p className="mt-2 text-2xl font-bold text-orange-600">
                    {result.areaSqFt.toFixed(2)}
                  </p>

                  <p className="text-sm text-gray-600">
                    sq ft
                  </p>
                </div>

                <div className="rounded-2xl bg-amber-50 p-5">
                  <p className="text-sm text-gray-500">
                    Paving Area
                  </p>

                  <p className="mt-2 text-2xl font-bold text-orange-600">
                    {result.areaSqM.toFixed(2)}
                  </p>

                  <p className="text-sm text-gray-600">
                    sq m
                  </p>
                </div>

                <div className="rounded-2xl bg-orange-50 p-5">
                  <p className="text-sm text-gray-500">
                    Asphalt Volume
                  </p>

                  <p className="mt-2 text-2xl font-bold text-orange-600">
                    {result.volumeCuFt.toFixed(2)}
                  </p>

                  <p className="text-sm text-gray-600">
                    cubic ft
                  </p>
                </div>

                <div className="rounded-2xl bg-amber-50 p-5">
                  <p className="text-sm text-gray-500">
                    Asphalt Volume
                  </p>

                  <p className="mt-2 text-2xl font-bold text-orange-600">
                    {result.volumeCuM.toFixed(2)}
                  </p>

                  <p className="text-sm text-gray-600">
                    cubic m
                  </p>
                </div>

                <div className="rounded-2xl bg-orange-50 p-5">
                  <p className="text-sm text-gray-500">
                    Estimated Weight
                  </p>

                  <p className="mt-2 text-2xl font-bold text-orange-600">
                    {result.weightKg.toFixed(0)}
                  </p>

                  <p className="text-sm text-gray-600">
                    kg
                  </p>
                </div>

                <div className="rounded-2xl bg-amber-50 p-5">
                  <p className="text-sm text-gray-500">
                    Estimated Weight
                  </p>

                  <p className="mt-2 text-2xl font-bold text-orange-600">
                    {result.weightTons.toFixed(2)}
                  </p>

                  <p className="text-sm text-gray-600">
                    US tons
                  </p>
                </div>
              </div>

              <p className="mt-6 leading-7 text-gray-600">
                The calculated volume represents
                the compact pavement volume
                based on the dimensions you
                entered. The weight is an
                estimate based on the assumed
                asphalt density shown above.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white transition hover:bg-black"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* FORMULA */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Asphalt Calculation Formula
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            Asphalt quantity is generally
            estimated by calculating the
            paving area first and then
            multiplying that area by the
            pavement thickness.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Volume Formula
            </h3>

            <p className="mt-3 text-lg font-semibold text-orange-600">
              Volume = Length × Width ×
              Thickness
            </p>

            <p className="mt-4 text-gray-600">
              Make sure all three dimensions
              use compatible units before
              multiplying them.
            </p>
          </div>

          <div className="mt-5 rounded-2xl border border-orange-100 bg-white p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Weight Formula
            </h3>

            <p className="mt-3 text-lg font-semibold text-orange-600">
              Weight = Volume × Asphalt
              Density
            </p>

            <p className="mt-4 text-gray-600">
              This calculator uses an assumed
              density of approximately
              2,323 kg/m³ for the estimated
              asphalt weight.
            </p>
          </div>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How to Use the Asphalt
            Calculator
          </h2>

          <div className="mt-6 space-y-5">
            <div>
              <h3 className="text-xl font-semibold text-gray-900">
                1. Enter the project length
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Enter the total length of the
                road, driveway, parking area,
                or other paved surface.
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-gray-900">
                2. Enter the project width
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Enter the average width of
                the area that will receive
                asphalt.
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-gray-900">
                3. Enter pavement thickness
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Enter the planned asphalt
                thickness and select whether
                it is measured in inches,
                feet, centimeters, or meters.
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-gray-900">
                4. Review the estimate
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                The calculator converts the
                dimensions into compatible
                units and displays area,
                volume, estimated weight in
                kilograms, and estimated US
                tons.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* EXAMPLE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Asphalt Calculation Example
          </h2>

          <p className="mt-4 leading-7 text-gray-600">
            Suppose a driveway is 50 feet
            long and 20 feet wide, with an
            asphalt thickness of 4 inches.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <p className="font-medium text-gray-900">
              Length = 50 ft
            </p>

            <p className="mt-2 font-medium text-gray-900">
              Width = 20 ft
            </p>

            <p className="mt-2 font-medium text-gray-900">
              Thickness = 4 inches
            </p>

            <p className="mt-4 font-semibold text-orange-600">
              Area = 50 × 20 = 1,000 sq ft
            </p>

            <p className="mt-3 text-gray-600">
              Since 4 inches equals 0.3333
              feet, the volume is
              approximately:
            </p>

            <p className="mt-3 font-semibold text-orange-600">
              Volume ≈ 1,000 × 0.3333 =
              333.33 cubic ft
            </p>
          </div>

          <p className="mt-5 leading-7 text-gray-600">
            The calculator then converts this
            volume to cubic meters and uses
            the assumed asphalt density to
            estimate the material weight.
          </p>
        </div>
      </section>

      {/* COMMON THICKNESS */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Common Asphalt Thickness
            Considerations
          </h2>

          <p className="mt-4 leading-7 text-gray-600">
            Asphalt thickness depends on the
            type of project, expected traffic,
            existing base, climate, drainage,
            and engineering specifications.
            The values below are general
            planning references, not project
            specifications.
          </p>

          <div className="mt-6 overflow-x-auto">
            <table className="w-full min-w-[500px] border-collapse text-left">
              <thead>
                <tr className="border-b border-orange-200">
                  <th className="p-4 font-bold text-gray-900">
                    Project Type
                  </th>

                  <th className="p-4 font-bold text-gray-900">
                    Example Thickness
                  </th>

                  <th className="p-4 font-bold text-gray-900">
                    Planning Note
                  </th>
                </tr>
              </thead>

              <tbody>
                <tr className="border-b border-orange-100">
                  <td className="p-4 text-gray-600">
                    Residential driveway
                  </td>

                  <td className="p-4 text-gray-600">
                    2–4 in
                  </td>

                  <td className="p-4 text-gray-600">
                    Depends on traffic and base
                  </td>
                </tr>

                <tr className="border-b border-orange-100">
                  <td className="p-4 text-gray-600">
                    Parking area
                  </td>

                  <td className="p-4 text-gray-600">
                    3–5 in
                  </td>

                  <td className="p-4 text-gray-600">
                    Consider vehicle loading
                  </td>
                </tr>

                <tr>
                  <td className="p-4 text-gray-600">
                    Road or heavy-use pavement
                  </td>

                  <td className="p-4 text-gray-600">
                    Project specific
                  </td>

                  <td className="p-4 text-gray-600">
                    Use engineering specifications
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* MATERIAL PLANNING */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Asphalt Material Planning Tips
          </h2>

          <div className="mt-6 space-y-5">
            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Measure the actual paving area
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Break irregular areas into
                smaller rectangles or other
                measurable sections and add
                their areas together.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Check the planned thickness
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                A small change in pavement
                thickness can significantly
                change the required volume.
                Use the thickness specified
                for your project.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Account for project conditions
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Existing pavement, base
                preparation, compaction,
                surface levels, and drainage
                can affect the final material
                requirement.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Confirm the mix density
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Asphalt density varies between
                mixes. For purchasing and
                construction decisions, use the
                density supplied by the asphalt
                producer or project engineer.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* COMMON MISTAKES */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Common Asphalt Estimation
            Mistakes
          </h2>

          <div className="mt-6 space-y-4 text-gray-600">
            <p>
              <strong className="text-gray-900">
                1. Mixing units:
              </strong>{" "}
              Multiplying feet, meters, and
              inches without conversion can
              produce a major error.
            </p>

            <p>
              <strong className="text-gray-900">
                2. Forgetting thickness:
              </strong>{" "}
              Area alone does not tell you the
              asphalt volume required.
            </p>

            <p>
              <strong className="text-gray-900">
                3. Assuming weight is exact:
              </strong>{" "}
              Asphalt density varies, so the
              tonnage shown by a calculator is
              an estimate unless the actual mix
              density is known.
            </p>

            <p>
              <strong className="text-gray-900">
                4. Ignoring site conditions:
              </strong>{" "}
              Base preparation, compaction,
              drainage, and grade can affect
              actual material requirements.
            </p>
          </div>
        </div>
      </section>

      {/* WHEN TO USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Where an Asphalt Calculator
            Can Help
          </h2>

          <p className="mt-4 leading-8 text-gray-600">
            An asphalt quantity estimate can
            be useful during early planning
            for residential driveways,
            parking areas, private roads,
            pathways, small paving projects,
            resurfacing work, and other
            construction applications.
          </p>

          <p className="mt-4 leading-8 text-gray-600">
            Contractors and homeowners can use
            the estimate to understand the
            approximate material volume before
            requesting supplier quotations.
            Final quantities should be checked
            against project drawings,
            specifications, and supplier
            recommendations.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">
            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What does an asphalt
                calculator calculate?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                It estimates the paving area,
                asphalt volume, and approximate
                material weight using the
                length, width, and pavement
                thickness you enter.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                How do I calculate asphalt
                volume?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Multiply the paving length by
                the width and then multiply the
                resulting area by the asphalt
                thickness. All dimensions should
                be converted to compatible units
                before multiplication.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                How much asphalt do I need for
                a driveway?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                The amount depends on the
                driveway area and planned
                pavement thickness. Enter both
                dimensions and the specified
                thickness into the calculator to
                estimate the volume.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                How many tons of asphalt do I
                need?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Asphalt tonnage depends on
                volume and density. This
                calculator estimates the weight
                using approximately 2,323 kg/m³,
                but the actual mix density should
                be confirmed with your supplier.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I calculate asphalt in
                cubic feet?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Yes. The calculator displays
                the estimated asphalt volume in
                both cubic feet and cubic
                meters.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I enter thickness in
                inches?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Yes. You can enter asphalt
                thickness in inches, feet,
                centimeters, or meters.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is the asphalt weight exact?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                No. The displayed weight is an
                estimate based on an assumed
                density. Actual asphalt density
                can vary depending on the mix
                and project conditions.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 bg-white p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this asphalt calculator
                free?
              </h3>

              <p className="mt-2 leading-7 text-gray-600">
                Yes. The CalHub asphalt
                calculator is free to use
                online, and the result can also
                be saved as a PDF report.
              </p>
            </div>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}