"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import RelatedCalculators from "../components/RelatedCalculators";

export default function AsphaltCalculatorClient() {
  const [length, setLength] =
    useState("");

  const [width, setWidth] =
    useState("");

  const [thickness, setThickness] =
    useState("");

  const [lengthUnit, setLengthUnit] =
    useState("ft");

  const [widthUnit, setWidthUnit] =
    useState("ft");

  const [thicknessUnit, setThicknessUnit] =
    useState("inch");

  const [result, setResult] =
    useState<number | null>(null);

  const calculateAsphalt = () => {
    if (
      !length ||
      !width ||
      !thickness
    )
      return;

    const volume =
      parseFloat(length) *
      parseFloat(width) *
      parseFloat(thickness);

    setResult(volume);
  };

  const resetCalculator = () => {
    setLength("");
    setWidth("");
    setThickness("");
    setLengthUnit("ft");
    setWidthUnit("ft");
    setThicknessUnit("inch");
    setResult(null);
  };

  const getVolumeUnit = () => {
    if (
      lengthUnit === "m" &&
      widthUnit === "m"
    ) {
      return "cubic meters";
    }

    return "cubic feet";
  };

  const downloadPDF = () => {
    if (result === null) return;

    const doc = new jsPDF();

    doc.setFontSize(20);

    doc.text(
      "Asphalt Calculation Report",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      `Length: ${length} ${lengthUnit}`,
      20,
      40
    );

    doc.text(
      `Width: ${width} ${widthUnit}`,
      20,
      50
    );

    doc.text(
      `Thickness: ${thickness} ${thicknessUnit}`,
      20,
      60
    );

    doc.text(
      `Asphalt Volume: ${result.toFixed(
        2
      )} ${getVolumeUnit()}`,
      20,
      75
    );

    doc.text(
      "Generated by CalHub.in",
      20,
      100
    );

    doc.save(
      "asphalt-calculation-report.pdf"
    );
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50">
      <Navbar />

      {/* HERO */}
      <section className="mx-auto max-w-2xl px-6 py-16">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 md:text-5xl">
            Asphalt Calculator
          </h1>

          <p className="mt-4 text-lg text-gray-600">
            Estimate asphalt quantity
            required for roads,
            driveways, parking lots, and
            paving projects instantly.
          </p>
        </div>

        {/* CALCULATOR */}
        <div className="mt-10 rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          {/* LENGTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Length
            </label>

            <input
              type="number"
              min="0"
              value={length}
              onChange={(e) =>
                setLength(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter length"
            />

            <select
              value={lengthUnit}
              onChange={(e) =>
                setLengthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* WIDTH */}
          <div className="mb-5">
            <label className="mb-2 block font-medium text-gray-700">
              Width
            </label>

            <input
              type="number"
              min="0"
              value={width}
              onChange={(e) =>
                setWidth(e.target.value)
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter width"
            />

            <select
              value={widthUnit}
              onChange={(e) =>
                setWidthUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="ft">
                Feet (ft)
              </option>

              <option value="m">
                Meter (m)
              </option>
            </select>
          </div>

          {/* THICKNESS */}
          <div className="mb-6">
            <label className="mb-2 block font-medium text-gray-700">
              Thickness
            </label>

            <input
              type="number"
              min="0"
              value={thickness}
              onChange={(e) =>
                setThickness(
                  e.target.value
                )
              }
              className="w-full rounded-2xl border border-orange-200 p-3"
              placeholder="Enter thickness"
            />

            <select
              value={thicknessUnit}
              onChange={(e) =>
                setThicknessUnit(
                  e.target.value
                )
              }
              className="mt-3 w-full rounded-2xl border border-orange-200 p-3"
            >
              <option value="inch">
                Inch
              </option>

              <option value="ft">
                Feet
              </option>

              <option value="cm">
                Centimeter
              </option>
            </select>
          </div>

          {/* BUTTONS */}
          <div className="flex gap-4">
            <button
              onClick={calculateAsphalt}
              className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 py-3 font-semibold text-white"
            >
              Calculate Asphalt
            </button>

            <button
              onClick={resetCalculator}
              className="w-full rounded-2xl border border-orange-300 bg-white py-3 font-semibold text-gray-700"
            >
              Reset
            </button>
          </div>

          {/* RESULT */}
          {result !== null && (
            <div className="mt-6 rounded-2xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-inner">
              <h2 className="text-2xl font-bold text-gray-900">
                Asphalt Volume:{" "}
                {result.toFixed(2)}{" "}
                {getVolumeUnit()}
              </h2>

              <p className="mt-3 text-gray-600">
                This estimated asphalt
                quantity can help with
                paving, resurfacing, road
                construction, and
                driveway planning.
              </p>

              <button
                onClick={downloadPDF}
                className="mt-5 w-full rounded-2xl bg-gray-900 py-3 font-semibold text-white"
              >
                Download PDF Report
              </button>
            </div>
          )}
        </div>
      </section>

      {/* CONTENT */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Asphalt Quantity Estimation
          </h2>

          <p className="mt-4 text-gray-600">
            This asphalt calculator helps
            estimate asphalt quantity for
            paving roads, parking lots,
            highways, and driveways.
          </p>

          <p className="mt-4 text-gray-600">
            Accurate asphalt estimation
            helps reduce material waste
            and improves construction
            planning efficiency.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Formula
            </h3>

            <p className="mt-3 text-lg font-medium text-orange-600">
              Volume = Length × Width ×
              Thickness
            </p>
          </div>
        </div>
      </section>

      {/* HOW TO USE */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            How to Use This Asphalt
            Calculator
          </h2>

          <p className="mt-4 text-gray-600">
            Enter the project length,
            width, and asphalt thickness,
            then click calculate to get
            the estimated asphalt volume.
          </p>

          <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-5">
            <h3 className="text-2xl font-semibold text-gray-900">
              Example
            </h3>

            <p className="mt-3 text-gray-600">
              50 ft × 20 ft × 4 inch
            </p>

            <p className="mt-3 font-medium text-orange-600">
              Estimated asphalt volume =
              4000 cubic feet
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 pb-20">
        <div className="rounded-3xl bg-gradient-to-br from-orange-50 via-white to-amber-50 p-8 shadow-xl">
          <h2 className="text-3xl font-bold text-gray-900">
            Frequently Asked Questions
          </h2>

          <div className="mt-8 space-y-6">
            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                What is an asphalt
                calculator?
              </h3>

              <p className="mt-2 text-gray-600">
                It helps estimate asphalt
                quantity needed for road
                and paving construction
                projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Can I use this for
                driveways?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes, it works for
                driveways, parking lots,
                roads, and resurfacing
                projects.
              </p>
            </div>

            <div className="rounded-2xl border border-orange-100 p-5">
              <h3 className="text-xl font-semibold text-gray-900">
                Is this calculator free?
              </h3>

              <p className="mt-2 text-gray-600">
                Yes, all calculators on
                CalHub are free to use.
              </p>
            </div>
          </div>
        </div>
      </section>

      <RelatedCalculators />

      <Footer />
    </main>
  );
}